// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	fmt "fmt"

	v1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	v2alpha1 "github.com/posit-dev/team-operator/api/keycloak/v2alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=core, Version=v1beta1
	case v1beta1.SchemeGroupVersion.WithResource("chronicles"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().Chronicles().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("connects"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().Connects().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("flightdecks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().Flightdecks().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("packagemanagers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().PackageManagers().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("postgresdatabases"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().PostgresDatabases().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("sites"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().Sites().Informer()}, nil
	case v1beta1.SchemeGroupVersion.WithResource("workbenches"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1beta1().Workbenches().Informer()}, nil

		// Group=keycloak, Version=v2alpha1
	case v2alpha1.SchemeGroupVersion.WithResource("keycloaks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Keycloak().V2alpha1().Keycloaks().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
