// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// KeycloakUnsupportedSpecApplyConfiguration represents a declarative configuration of the KeycloakUnsupportedSpec type for use
// with apply.
type KeycloakUnsupportedSpecApplyConfiguration struct {
	PodTemplate *v1.PodTemplateSpec `json:"podTemplate,omitempty"`
}

// KeycloakUnsupportedSpecApplyConfiguration constructs a declarative configuration of the KeycloakUnsupportedSpec type for use with
// apply.
func KeycloakUnsupportedSpec() *KeycloakUnsupportedSpecApplyConfiguration {
	return &KeycloakUnsupportedSpecApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *KeycloakUnsupportedSpecApplyConfiguration) WithPodTemplate(value v1.PodTemplateSpec) *KeycloakUnsupportedSpecApplyConfiguration {
	b.PodTemplate = &value
	return b
}
