// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// KeycloakDbSpecApplyConfiguration represents a declarative configuration of the KeycloakDbSpec type for use
// with apply.
type KeycloakDbSpecApplyConfiguration struct {
	Vendor          *string                               `json:"vendor,omitempty"`
	UsernameSecret  *KeycloakSecretSpecApplyConfiguration `json:"usernameSecret,omitempty"`
	PasswordSecret  *KeycloakSecretSpecApplyConfiguration `json:"passwordSecret,omitempty"`
	Host            *string                               `json:"host,omitempty"`
	Database        *string                               `json:"database,omitempty"`
	Port            *int                                  `json:"port,omitempty"`
	Schema          *string                               `json:"schema,omitempty"`
	PoolInitialSize *int                                  `json:"poolInitialSize,omitempty"`
	PoolMinSize     *int                                  `json:"poolMinSize,omitempty"`
	PoolMaxSize     *int                                  `json:"poolMaxSize,omitempty"`
}

// KeycloakDbSpecApplyConfiguration constructs a declarative configuration of the KeycloakDbSpec type for use with
// apply.
func KeycloakDbSpec() *KeycloakDbSpecApplyConfiguration {
	return &KeycloakDbSpecApplyConfiguration{}
}

// WithVendor sets the Vendor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vendor field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithVendor(value string) *KeycloakDbSpecApplyConfiguration {
	b.Vendor = &value
	return b
}

// WithUsernameSecret sets the UsernameSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsernameSecret field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithUsernameSecret(value *KeycloakSecretSpecApplyConfiguration) *KeycloakDbSpecApplyConfiguration {
	b.UsernameSecret = value
	return b
}

// WithPasswordSecret sets the PasswordSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordSecret field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithPasswordSecret(value *KeycloakSecretSpecApplyConfiguration) *KeycloakDbSpecApplyConfiguration {
	b.PasswordSecret = value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithHost(value string) *KeycloakDbSpecApplyConfiguration {
	b.Host = &value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithDatabase(value string) *KeycloakDbSpecApplyConfiguration {
	b.Database = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithPort(value int) *KeycloakDbSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithSchema sets the Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schema field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithSchema(value string) *KeycloakDbSpecApplyConfiguration {
	b.Schema = &value
	return b
}

// WithPoolInitialSize sets the PoolInitialSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolInitialSize field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithPoolInitialSize(value int) *KeycloakDbSpecApplyConfiguration {
	b.PoolInitialSize = &value
	return b
}

// WithPoolMinSize sets the PoolMinSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolMinSize field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithPoolMinSize(value int) *KeycloakDbSpecApplyConfiguration {
	b.PoolMinSize = &value
	return b
}

// WithPoolMaxSize sets the PoolMaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolMaxSize field is set to the value of the last call.
func (b *KeycloakDbSpecApplyConfiguration) WithPoolMaxSize(value int) *KeycloakDbSpecApplyConfiguration {
	b.PoolMaxSize = &value
	return b
}
