// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// KeycloakIngressSpecApplyConfiguration represents a declarative configuration of the KeycloakIngressSpec type for use
// with apply.
type KeycloakIngressSpecApplyConfiguration struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	ClassName   *string           `json:"className,omitempty"`
	Enabled     *bool             `json:"enabled,omitempty"`
}

// KeycloakIngressSpecApplyConfiguration constructs a declarative configuration of the KeycloakIngressSpec type for use with
// apply.
func KeycloakIngressSpec() *KeycloakIngressSpecApplyConfiguration {
	return &KeycloakIngressSpecApplyConfiguration{}
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *KeycloakIngressSpecApplyConfiguration) WithAnnotations(entries map[string]string) *KeycloakIngressSpecApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithClassName sets the ClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClassName field is set to the value of the last call.
func (b *KeycloakIngressSpecApplyConfiguration) WithClassName(value string) *KeycloakIngressSpecApplyConfiguration {
	b.ClassName = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *KeycloakIngressSpecApplyConfiguration) WithEnabled(value bool) *KeycloakIngressSpecApplyConfiguration {
	b.Enabled = &value
	return b
}
