// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// KeycloakFeaturesSpecApplyConfiguration represents a declarative configuration of the KeycloakFeaturesSpec type for use
// with apply.
type KeycloakFeaturesSpecApplyConfiguration struct {
	Enabled  []string `json:"enabled,omitempty"`
	Disabled []string `json:"disabled,omitempty"`
}

// KeycloakFeaturesSpecApplyConfiguration constructs a declarative configuration of the KeycloakFeaturesSpec type for use with
// apply.
func KeycloakFeaturesSpec() *KeycloakFeaturesSpecApplyConfiguration {
	return &KeycloakFeaturesSpecApplyConfiguration{}
}

// WithEnabled adds the given value to the Enabled field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Enabled field.
func (b *KeycloakFeaturesSpecApplyConfiguration) WithEnabled(values ...string) *KeycloakFeaturesSpecApplyConfiguration {
	for i := range values {
		b.Enabled = append(b.Enabled, values[i])
	}
	return b
}

// WithDisabled adds the given value to the Disabled field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Disabled field.
func (b *KeycloakFeaturesSpecApplyConfiguration) WithDisabled(values ...string) *KeycloakFeaturesSpecApplyConfiguration {
	for i := range values {
		b.Disabled = append(b.Disabled, values[i])
	}
	return b
}
