// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// KeycloakHttpSpecApplyConfiguration represents a declarative configuration of the KeycloakHttpSpec type for use
// with apply.
type KeycloakHttpSpecApplyConfiguration struct {
	HttpEnabled *bool   `json:"httpEnabled,omitempty"`
	HttpPort    *int    `json:"httpPort,omitempty"`
	HttpsPort   *int    `json:"httpsPort,omitempty"`
	TlsSecret   *string `json:"tlsSecret,omitempty"`
}

// KeycloakHttpSpecApplyConfiguration constructs a declarative configuration of the KeycloakHttpSpec type for use with
// apply.
func KeycloakHttpSpec() *KeycloakHttpSpecApplyConfiguration {
	return &KeycloakHttpSpecApplyConfiguration{}
}

// WithHttpEnabled sets the HttpEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HttpEnabled field is set to the value of the last call.
func (b *KeycloakHttpSpecApplyConfiguration) WithHttpEnabled(value bool) *KeycloakHttpSpecApplyConfiguration {
	b.HttpEnabled = &value
	return b
}

// WithHttpPort sets the HttpPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HttpPort field is set to the value of the last call.
func (b *KeycloakHttpSpecApplyConfiguration) WithHttpPort(value int) *KeycloakHttpSpecApplyConfiguration {
	b.HttpPort = &value
	return b
}

// WithHttpsPort sets the HttpsPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HttpsPort field is set to the value of the last call.
func (b *KeycloakHttpSpecApplyConfiguration) WithHttpsPort(value int) *KeycloakHttpSpecApplyConfiguration {
	b.HttpsPort = &value
	return b
}

// WithTlsSecret sets the TlsSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TlsSecret field is set to the value of the last call.
func (b *KeycloakHttpSpecApplyConfiguration) WithTlsSecret(value string) *KeycloakHttpSpecApplyConfiguration {
	b.TlsSecret = &value
	return b
}
