// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// KeycloakTransactionSpecApplyConfiguration represents a declarative configuration of the KeycloakTransactionSpec type for use
// with apply.
type KeycloakTransactionSpecApplyConfiguration struct {
	XaEnabled *bool `json:"xaEnabled,omitempty"`
}

// KeycloakTransactionSpecApplyConfiguration constructs a declarative configuration of the KeycloakTransactionSpec type for use with
// apply.
func KeycloakTransactionSpec() *KeycloakTransactionSpecApplyConfiguration {
	return &KeycloakTransactionSpecApplyConfiguration{}
}

// WithXaEnabled sets the XaEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the XaEnabled field is set to the value of the last call.
func (b *KeycloakTransactionSpecApplyConfiguration) WithXaEnabled(value bool) *KeycloakTransactionSpecApplyConfiguration {
	b.XaEnabled = &value
	return b
}
