// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2alpha1

// KeycloakSpecApplyConfiguration represents a declarative configuration of the KeycloakSpec type for use
// with apply.
type KeycloakSpecApplyConfiguration struct {
	Db          *KeycloakDbSpecApplyConfiguration          `json:"db,omitempty"`
	Http        *KeycloakHttpSpecApplyConfiguration        `json:"http,omitempty"`
	Hostname    *KeycloakHostnameSpecApplyConfiguration    `json:"hostname,omitempty"`
	Features    *KeycloakFeaturesSpecApplyConfiguration    `json:"features,omitempty"`
	Transaction *KeycloakTransactionSpecApplyConfiguration `json:"transaction,omitempty"`
	Unsupported *KeycloakUnsupportedSpecApplyConfiguration `json:"unsupported,omitempty"`
	Ingress     *KeycloakIngressSpecApplyConfiguration     `json:"ingress,omitempty"`
	Instances   *int                                       `json:"instances,omitempty"`
	Image       *string                                    `json:"image,omitempty"`
}

// KeycloakSpecApplyConfiguration constructs a declarative configuration of the KeycloakSpec type for use with
// apply.
func KeycloakSpec() *KeycloakSpecApplyConfiguration {
	return &KeycloakSpecApplyConfiguration{}
}

// WithDb sets the Db field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Db field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithDb(value *KeycloakDbSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Db = value
	return b
}

// WithHttp sets the Http field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithHttp(value *KeycloakHttpSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Http = value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithHostname(value *KeycloakHostnameSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Hostname = value
	return b
}

// WithFeatures sets the Features field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Features field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithFeatures(value *KeycloakFeaturesSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Features = value
	return b
}

// WithTransaction sets the Transaction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transaction field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithTransaction(value *KeycloakTransactionSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Transaction = value
	return b
}

// WithUnsupported sets the Unsupported field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unsupported field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithUnsupported(value *KeycloakUnsupportedSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Unsupported = value
	return b
}

// WithIngress sets the Ingress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ingress field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithIngress(value *KeycloakIngressSpecApplyConfiguration) *KeycloakSpecApplyConfiguration {
	b.Ingress = value
	return b
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithInstances(value int) *KeycloakSpecApplyConfiguration {
	b.Instances = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *KeycloakSpecApplyConfiguration) WithImage(value string) *KeycloakSpecApplyConfiguration {
	b.Image = &value
	return b
}
