// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ChronicleListerExpansion allows custom methods to be added to
// ChronicleLister.
type ChronicleListerExpansion interface{}

// ChronicleNamespaceListerExpansion allows custom methods to be added to
// ChronicleNamespaceLister.
type ChronicleNamespaceListerExpansion interface{}

// ConnectListerExpansion allows custom methods to be added to
// ConnectLister.
type ConnectListerExpansion interface{}

// ConnectNamespaceListerExpansion allows custom methods to be added to
// ConnectNamespaceLister.
type ConnectNamespaceListerExpansion interface{}

// FlightdeckListerExpansion allows custom methods to be added to
// FlightdeckLister.
type FlightdeckListerExpansion interface{}

// FlightdeckNamespaceListerExpansion allows custom methods to be added to
// FlightdeckNamespaceLister.
type FlightdeckNamespaceListerExpansion interface{}

// PackageManagerListerExpansion allows custom methods to be added to
// PackageManagerLister.
type PackageManagerListerExpansion interface{}

// PackageManagerNamespaceListerExpansion allows custom methods to be added to
// PackageManagerNamespaceLister.
type PackageManagerNamespaceListerExpansion interface{}

// PostgresDatabaseListerExpansion allows custom methods to be added to
// PostgresDatabaseLister.
type PostgresDatabaseListerExpansion interface{}

// PostgresDatabaseNamespaceListerExpansion allows custom methods to be added to
// PostgresDatabaseNamespaceLister.
type PostgresDatabaseNamespaceListerExpansion interface{}

// SiteListerExpansion allows custom methods to be added to
// SiteLister.
type SiteListerExpansion interface{}

// SiteNamespaceListerExpansion allows custom methods to be added to
// SiteNamespaceLister.
type SiteNamespaceListerExpansion interface{}

// WorkbenchListerExpansion allows custom methods to be added to
// WorkbenchLister.
type WorkbenchListerExpansion interface{}

// WorkbenchNamespaceListerExpansion allows custom methods to be added to
// WorkbenchNamespaceLister.
type WorkbenchNamespaceListerExpansion interface{}
