// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FlightdeckLister helps list Flightdecks.
// All objects returned here must be treated as read-only.
type FlightdeckLister interface {
	// List lists all Flightdecks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.Flightdeck, err error)
	// Flightdecks returns an object that can list and get Flightdecks.
	Flightdecks(namespace string) FlightdeckNamespaceLister
	FlightdeckListerExpansion
}

// flightdeckLister implements the FlightdeckLister interface.
type flightdeckLister struct {
	listers.ResourceIndexer[*corev1beta1.Flightdeck]
}

// NewFlightdeckLister returns a new FlightdeckLister.
func NewFlightdeckLister(indexer cache.Indexer) FlightdeckLister {
	return &flightdeckLister{listers.New[*corev1beta1.Flightdeck](indexer, corev1beta1.Resource("flightdeck"))}
}

// Flightdecks returns an object that can list and get Flightdecks.
func (s *flightdeckLister) Flightdecks(namespace string) FlightdeckNamespaceLister {
	return flightdeckNamespaceLister{listers.NewNamespaced[*corev1beta1.Flightdeck](s.ResourceIndexer, namespace)}
}

// FlightdeckNamespaceLister helps list and get Flightdecks.
// All objects returned here must be treated as read-only.
type FlightdeckNamespaceLister interface {
	// List lists all Flightdecks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.Flightdeck, err error)
	// Get retrieves the Flightdeck from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1beta1.Flightdeck, error)
	FlightdeckNamespaceListerExpansion
}

// flightdeckNamespaceLister implements the FlightdeckNamespaceLister
// interface.
type flightdeckNamespaceLister struct {
	listers.ResourceIndexer[*corev1beta1.Flightdeck]
}
