// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PackageManagerLister helps list PackageManagers.
// All objects returned here must be treated as read-only.
type PackageManagerLister interface {
	// List lists all PackageManagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.PackageManager, err error)
	// PackageManagers returns an object that can list and get PackageManagers.
	PackageManagers(namespace string) PackageManagerNamespaceLister
	PackageManagerListerExpansion
}

// packageManagerLister implements the PackageManagerLister interface.
type packageManagerLister struct {
	listers.ResourceIndexer[*corev1beta1.PackageManager]
}

// NewPackageManagerLister returns a new PackageManagerLister.
func NewPackageManagerLister(indexer cache.Indexer) PackageManagerLister {
	return &packageManagerLister{listers.New[*corev1beta1.PackageManager](indexer, corev1beta1.Resource("packagemanager"))}
}

// PackageManagers returns an object that can list and get PackageManagers.
func (s *packageManagerLister) PackageManagers(namespace string) PackageManagerNamespaceLister {
	return packageManagerNamespaceLister{listers.NewNamespaced[*corev1beta1.PackageManager](s.ResourceIndexer, namespace)}
}

// PackageManagerNamespaceLister helps list and get PackageManagers.
// All objects returned here must be treated as read-only.
type PackageManagerNamespaceLister interface {
	// List lists all PackageManagers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.PackageManager, err error)
	// Get retrieves the PackageManager from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1beta1.PackageManager, error)
	PackageManagerNamespaceListerExpansion
}

// packageManagerNamespaceLister implements the PackageManagerNamespaceLister
// interface.
type packageManagerNamespaceLister struct {
	listers.ResourceIndexer[*corev1beta1.PackageManager]
}
