// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PostgresDatabaseLister helps list PostgresDatabases.
// All objects returned here must be treated as read-only.
type PostgresDatabaseLister interface {
	// List lists all PostgresDatabases in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.PostgresDatabase, err error)
	// PostgresDatabases returns an object that can list and get PostgresDatabases.
	PostgresDatabases(namespace string) PostgresDatabaseNamespaceLister
	PostgresDatabaseListerExpansion
}

// postgresDatabaseLister implements the PostgresDatabaseLister interface.
type postgresDatabaseLister struct {
	listers.ResourceIndexer[*corev1beta1.PostgresDatabase]
}

// NewPostgresDatabaseLister returns a new PostgresDatabaseLister.
func NewPostgresDatabaseLister(indexer cache.Indexer) PostgresDatabaseLister {
	return &postgresDatabaseLister{listers.New[*corev1beta1.PostgresDatabase](indexer, corev1beta1.Resource("postgresdatabase"))}
}

// PostgresDatabases returns an object that can list and get PostgresDatabases.
func (s *postgresDatabaseLister) PostgresDatabases(namespace string) PostgresDatabaseNamespaceLister {
	return postgresDatabaseNamespaceLister{listers.NewNamespaced[*corev1beta1.PostgresDatabase](s.ResourceIndexer, namespace)}
}

// PostgresDatabaseNamespaceLister helps list and get PostgresDatabases.
// All objects returned here must be treated as read-only.
type PostgresDatabaseNamespaceLister interface {
	// List lists all PostgresDatabases in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.PostgresDatabase, err error)
	// Get retrieves the PostgresDatabase from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1beta1.PostgresDatabase, error)
	PostgresDatabaseNamespaceListerExpansion
}

// postgresDatabaseNamespaceLister implements the PostgresDatabaseNamespaceLister
// interface.
type postgresDatabaseNamespaceLister struct {
	listers.ResourceIndexer[*corev1beta1.PostgresDatabase]
}
