// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/posit-dev/team-operator/api/keycloak/v2alpha1"
	keycloakv2alpha1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/keycloak/v2alpha1"
	typedkeycloakv2alpha1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/keycloak/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeKeycloaks implements KeycloakInterface
type fakeKeycloaks struct {
	*gentype.FakeClientWithListAndApply[*v2alpha1.Keycloak, *v2alpha1.KeycloakList, *keycloakv2alpha1.KeycloakApplyConfiguration]
	Fake *FakeKeycloakV2alpha1
}

func newFakeKeycloaks(fake *FakeKeycloakV2alpha1, namespace string) typedkeycloakv2alpha1.KeycloakInterface {
	return &fakeKeycloaks{
		gentype.NewFakeClientWithListAndApply[*v2alpha1.Keycloak, *v2alpha1.KeycloakList, *keycloakv2alpha1.KeycloakApplyConfiguration](
			fake.Fake,
			namespace,
			v2alpha1.SchemeGroupVersion.WithResource("keycloaks"),
			v2alpha1.SchemeGroupVersion.WithKind("Keycloak"),
			func() *v2alpha1.Keycloak { return &v2alpha1.Keycloak{} },
			func() *v2alpha1.KeycloakList { return &v2alpha1.KeycloakList{} },
			func(dst, src *v2alpha1.KeycloakList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.KeycloakList) []*v2alpha1.Keycloak { return gentype.ToPointerSlice(list.Items) },
			func(list *v2alpha1.KeycloakList, items []*v2alpha1.Keycloak) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
