// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/keycloak/v2alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKeycloakV2alpha1 struct {
	*testing.Fake
}

func (c *FakeKeycloakV2alpha1) Keycloaks(namespace string) v2alpha1.KeycloakInterface {
	return newFakeKeycloaks(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKeycloakV2alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
