// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"
	time "time"

	apikeycloakv2alpha1 "github.com/posit-dev/team-operator/api/keycloak/v2alpha1"
	versioned "github.com/posit-dev/team-operator/client-go/clientset/versioned"
	internalinterfaces "github.com/posit-dev/team-operator/client-go/informers/externalversions/internalinterfaces"
	keycloakv2alpha1 "github.com/posit-dev/team-operator/client-go/listers/keycloak/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KeycloakInformer provides access to a shared informer and lister for
// Keycloaks.
type KeycloakInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() keycloakv2alpha1.KeycloakLister
}

type keycloakInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKeycloakInformer constructs a new informer for Keycloak type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKeycloakInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKeycloakInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKeycloakInformer constructs a new informer for Keycloak type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKeycloakInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeycloakV2alpha1().Keycloaks(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeycloakV2alpha1().Keycloaks(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeycloakV2alpha1().Keycloaks(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeycloakV2alpha1().Keycloaks(namespace).Watch(ctx, options)
			},
		},
		&apikeycloakv2alpha1.Keycloak{},
		resyncPeriod,
		indexers,
	)
}

func (f *keycloakInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKeycloakInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *keycloakInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apikeycloakv2alpha1.Keycloak{}, f.defaultInformer)
}

func (f *keycloakInformer) Lister() keycloakv2alpha1.KeycloakLister {
	return keycloakv2alpha1.NewKeycloakLister(f.Informer().GetIndexer())
}
