// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	typedcorev1beta1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/core/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeConnects implements ConnectInterface
type fakeConnects struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.Connect, *v1beta1.ConnectList, *corev1beta1.ConnectApplyConfiguration]
	Fake *FakeCoreV1beta1
}

func newFakeConnects(fake *FakeCoreV1beta1, namespace string) typedcorev1beta1.ConnectInterface {
	return &fakeConnects{
		gentype.NewFakeClientWithListAndApply[*v1beta1.Connect, *v1beta1.ConnectList, *corev1beta1.ConnectApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("connects"),
			v1beta1.SchemeGroupVersion.WithKind("Connect"),
			func() *v1beta1.Connect { return &v1beta1.Connect{} },
			func() *v1beta1.ConnectList { return &v1beta1.ConnectList{} },
			func(dst, src *v1beta1.ConnectList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ConnectList) []*v1beta1.Connect { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.ConnectList, items []*v1beta1.Connect) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
