// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	typedcorev1beta1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/core/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFlightdecks implements FlightdeckInterface
type fakeFlightdecks struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.Flightdeck, *v1beta1.FlightdeckList, *corev1beta1.FlightdeckApplyConfiguration]
	Fake *FakeCoreV1beta1
}

func newFakeFlightdecks(fake *FakeCoreV1beta1, namespace string) typedcorev1beta1.FlightdeckInterface {
	return &fakeFlightdecks{
		gentype.NewFakeClientWithListAndApply[*v1beta1.Flightdeck, *v1beta1.FlightdeckList, *corev1beta1.FlightdeckApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("flightdecks"),
			v1beta1.SchemeGroupVersion.WithKind("Flightdeck"),
			func() *v1beta1.Flightdeck { return &v1beta1.Flightdeck{} },
			func() *v1beta1.FlightdeckList { return &v1beta1.FlightdeckList{} },
			func(dst, src *v1beta1.FlightdeckList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.FlightdeckList) []*v1beta1.Flightdeck { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.FlightdeckList, items []*v1beta1.Flightdeck) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
