// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	typedcorev1beta1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/core/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSites implements SiteInterface
type fakeSites struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.Site, *v1beta1.SiteList, *corev1beta1.SiteApplyConfiguration]
	Fake *FakeCoreV1beta1
}

func newFakeSites(fake *FakeCoreV1beta1, namespace string) typedcorev1beta1.SiteInterface {
	return &fakeSites{
		gentype.NewFakeClientWithListAndApply[*v1beta1.Site, *v1beta1.SiteList, *corev1beta1.SiteApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("sites"),
			v1beta1.SchemeGroupVersion.WithKind("Site"),
			func() *v1beta1.Site { return &v1beta1.Site{} },
			func() *v1beta1.SiteList { return &v1beta1.SiteList{} },
			func(dst, src *v1beta1.SiteList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.SiteList) []*v1beta1.Site { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.SiteList, items []*v1beta1.Site) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
