// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	typedcorev1beta1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/core/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakePostgresDatabases implements PostgresDatabaseInterface
type fakePostgresDatabases struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.PostgresDatabase, *v1beta1.PostgresDatabaseList, *corev1beta1.PostgresDatabaseApplyConfiguration]
	Fake *FakeCoreV1beta1
}

func newFakePostgresDatabases(fake *FakeCoreV1beta1, namespace string) typedcorev1beta1.PostgresDatabaseInterface {
	return &fakePostgresDatabases{
		gentype.NewFakeClientWithListAndApply[*v1beta1.PostgresDatabase, *v1beta1.PostgresDatabaseList, *corev1beta1.PostgresDatabaseApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("postgresdatabases"),
			v1beta1.SchemeGroupVersion.WithKind("PostgresDatabase"),
			func() *v1beta1.PostgresDatabase { return &v1beta1.PostgresDatabase{} },
			func() *v1beta1.PostgresDatabaseList { return &v1beta1.PostgresDatabaseList{} },
			func(dst, src *v1beta1.PostgresDatabaseList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.PostgresDatabaseList) []*v1beta1.PostgresDatabase {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.PostgresDatabaseList, items []*v1beta1.PostgresDatabase) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
