// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	typedcorev1beta1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/core/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeChronicles implements ChronicleInterface
type fakeChronicles struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.Chronicle, *v1beta1.ChronicleList, *corev1beta1.ChronicleApplyConfiguration]
	Fake *FakeCoreV1beta1
}

func newFakeChronicles(fake *FakeCoreV1beta1, namespace string) typedcorev1beta1.ChronicleInterface {
	return &fakeChronicles{
		gentype.NewFakeClientWithListAndApply[*v1beta1.Chronicle, *v1beta1.ChronicleList, *corev1beta1.ChronicleApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("chronicles"),
			v1beta1.SchemeGroupVersion.WithKind("Chronicle"),
			func() *v1beta1.Chronicle { return &v1beta1.Chronicle{} },
			func() *v1beta1.ChronicleList { return &v1beta1.ChronicleList{} },
			func(dst, src *v1beta1.ChronicleList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ChronicleList) []*v1beta1.Chronicle { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.ChronicleList, items []*v1beta1.Chronicle) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
