// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/posit-dev/team-operator/client-go/clientset/versioned/typed/core/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCoreV1beta1 struct {
	*testing.Fake
}

func (c *FakeCoreV1beta1) Chronicles(namespace string) v1beta1.ChronicleInterface {
	return newFakeChronicles(c, namespace)
}

func (c *FakeCoreV1beta1) Connects(namespace string) v1beta1.ConnectInterface {
	return newFakeConnects(c, namespace)
}

func (c *FakeCoreV1beta1) Flightdecks(namespace string) v1beta1.FlightdeckInterface {
	return newFakeFlightdecks(c, namespace)
}

func (c *FakeCoreV1beta1) PackageManagers(namespace string) v1beta1.PackageManagerInterface {
	return newFakePackageManagers(c, namespace)
}

func (c *FakeCoreV1beta1) PostgresDatabases(namespace string) v1beta1.PostgresDatabaseInterface {
	return newFakePostgresDatabases(c, namespace)
}

func (c *FakeCoreV1beta1) Sites(namespace string) v1beta1.SiteInterface {
	return newFakeSites(c, namespace)
}

func (c *FakeCoreV1beta1) Workbenches(namespace string) v1beta1.WorkbenchInterface {
	return newFakeWorkbenches(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCoreV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
