// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apicorev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	versioned "github.com/posit-dev/team-operator/client-go/clientset/versioned"
	internalinterfaces "github.com/posit-dev/team-operator/client-go/informers/externalversions/internalinterfaces"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/listers/core/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ChronicleInformer provides access to a shared informer and lister for
// Chronicles.
type ChronicleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1beta1.ChronicleLister
}

type chronicleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewChronicleInformer constructs a new informer for Chronicle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewChronicleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredChronicleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredChronicleInformer constructs a new informer for Chronicle type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredChronicleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().Chronicles(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().Chronicles(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().Chronicles(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().Chronicles(namespace).Watch(ctx, options)
			},
		},
		&apicorev1beta1.Chronicle{},
		resyncPeriod,
		indexers,
	)
}

func (f *chronicleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredChronicleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *chronicleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1beta1.Chronicle{}, f.defaultInformer)
}

func (f *chronicleInformer) Lister() corev1beta1.ChronicleLister {
	return corev1beta1.NewChronicleLister(f.Informer().GetIndexer())
}
