// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apicorev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	versioned "github.com/posit-dev/team-operator/client-go/clientset/versioned"
	internalinterfaces "github.com/posit-dev/team-operator/client-go/informers/externalversions/internalinterfaces"
	corev1beta1 "github.com/posit-dev/team-operator/client-go/listers/core/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PostgresDatabaseInformer provides access to a shared informer and lister for
// PostgresDatabases.
type PostgresDatabaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1beta1.PostgresDatabaseLister
}

type postgresDatabaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPostgresDatabaseInformer constructs a new informer for PostgresDatabase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPostgresDatabaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPostgresDatabaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPostgresDatabaseInformer constructs a new informer for PostgresDatabase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPostgresDatabaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().PostgresDatabases(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().PostgresDatabases(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().PostgresDatabases(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().PostgresDatabases(namespace).Watch(ctx, options)
			},
		},
		&apicorev1beta1.PostgresDatabase{},
		resyncPeriod,
		indexers,
	)
}

func (f *postgresDatabaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPostgresDatabaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *postgresDatabaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicorev1beta1.PostgresDatabase{}, f.defaultInformer)
}

func (f *postgresDatabaseInformer) Lister() corev1beta1.PostgresDatabaseLister {
	return corev1beta1.NewPostgresDatabaseLister(f.Informer().GetIndexer())
}
