// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ApiSettingsConfigApplyConfiguration represents a declarative configuration of the ApiSettingsConfig type for use
// with apply.
type ApiSettingsConfigApplyConfiguration struct {
	WorkbenchApiEnabled           *int `json:"workbenchApiEnabled,omitempty"`
	WorkbenchApiAdminEnabled      *int `json:"workbenchApiAdminEnabled,omitempty"`
	WorkbenchApiSuperAdminEnabled *int `json:"workbenchApiSuperAdminEnabled,omitempty"`
}

// ApiSettingsConfigApplyConfiguration constructs a declarative configuration of the ApiSettingsConfig type for use with
// apply.
func ApiSettingsConfig() *ApiSettingsConfigApplyConfiguration {
	return &ApiSettingsConfigApplyConfiguration{}
}

// WithWorkbenchApiEnabled sets the WorkbenchApiEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkbenchApiEnabled field is set to the value of the last call.
func (b *ApiSettingsConfigApplyConfiguration) WithWorkbenchApiEnabled(value int) *ApiSettingsConfigApplyConfiguration {
	b.WorkbenchApiEnabled = &value
	return b
}

// WithWorkbenchApiAdminEnabled sets the WorkbenchApiAdminEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkbenchApiAdminEnabled field is set to the value of the last call.
func (b *ApiSettingsConfigApplyConfiguration) WithWorkbenchApiAdminEnabled(value int) *ApiSettingsConfigApplyConfiguration {
	b.WorkbenchApiAdminEnabled = &value
	return b
}

// WithWorkbenchApiSuperAdminEnabled sets the WorkbenchApiSuperAdminEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkbenchApiSuperAdminEnabled field is set to the value of the last call.
func (b *ApiSettingsConfigApplyConfiguration) WithWorkbenchApiSuperAdminEnabled(value int) *ApiSettingsConfigApplyConfiguration {
	b.WorkbenchApiSuperAdminEnabled = &value
	return b
}
