// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AuditedJobsConfigApplyConfiguration represents a declarative configuration of the AuditedJobsConfig type for use
// with apply.
type AuditedJobsConfigApplyConfiguration struct {
	Enabled            *int    `json:"enabled,omitempty"`
	StoragePath        *string `json:"storagePath,omitempty"`
	PrivateKeyPath     *string `json:"privateKeyPath,omitempty"`
	PublicKeyPaths     *string `json:"publicKeyPaths,omitempty"`
	LogLimit           *int    `json:"logLimit,omitempty"`
	DeletionExpiry     *int    `json:"deletionExpiry,omitempty"`
	VanillaRequired    *int    `json:"vanillaRequired,omitempty"`
	DetailsEnvironment *int    `json:"detailsEnvironment,omitempty"`
	DetailsUserDefined *int    `json:"detailsUserDefined,omitempty"`
}

// AuditedJobsConfigApplyConfiguration constructs a declarative configuration of the AuditedJobsConfig type for use with
// apply.
func AuditedJobsConfig() *AuditedJobsConfigApplyConfiguration {
	return &AuditedJobsConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithEnabled(value int) *AuditedJobsConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithStoragePath sets the StoragePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StoragePath field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithStoragePath(value string) *AuditedJobsConfigApplyConfiguration {
	b.StoragePath = &value
	return b
}

// WithPrivateKeyPath sets the PrivateKeyPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeyPath field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithPrivateKeyPath(value string) *AuditedJobsConfigApplyConfiguration {
	b.PrivateKeyPath = &value
	return b
}

// WithPublicKeyPaths sets the PublicKeyPaths field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicKeyPaths field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithPublicKeyPaths(value string) *AuditedJobsConfigApplyConfiguration {
	b.PublicKeyPaths = &value
	return b
}

// WithLogLimit sets the LogLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLimit field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithLogLimit(value int) *AuditedJobsConfigApplyConfiguration {
	b.LogLimit = &value
	return b
}

// WithDeletionExpiry sets the DeletionExpiry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionExpiry field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithDeletionExpiry(value int) *AuditedJobsConfigApplyConfiguration {
	b.DeletionExpiry = &value
	return b
}

// WithVanillaRequired sets the VanillaRequired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VanillaRequired field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithVanillaRequired(value int) *AuditedJobsConfigApplyConfiguration {
	b.VanillaRequired = &value
	return b
}

// WithDetailsEnvironment sets the DetailsEnvironment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DetailsEnvironment field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithDetailsEnvironment(value int) *AuditedJobsConfigApplyConfiguration {
	b.DetailsEnvironment = &value
	return b
}

// WithDetailsUserDefined sets the DetailsUserDefined field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DetailsUserDefined field is set to the value of the last call.
func (b *AuditedJobsConfigApplyConfiguration) WithDetailsUserDefined(value int) *AuditedJobsConfigApplyConfiguration {
	b.DetailsUserDefined = &value
	return b
}
