// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AzureFilesConfigApplyConfiguration represents a declarative configuration of the AzureFilesConfig type for use
// with apply.
type AzureFilesConfigApplyConfiguration struct {
	StorageClassName *string `json:"storageClassName,omitempty"`
	ShareSizeGiB     *int    `json:"shareSizeGiB,omitempty"`
}

// AzureFilesConfigApplyConfiguration constructs a declarative configuration of the AzureFilesConfig type for use with
// apply.
func AzureFilesConfig() *AzureFilesConfigApplyConfiguration {
	return &AzureFilesConfigApplyConfiguration{}
}

// WithStorageClassName sets the StorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClassName field is set to the value of the last call.
func (b *AzureFilesConfigApplyConfiguration) WithStorageClassName(value string) *AzureFilesConfigApplyConfiguration {
	b.StorageClassName = &value
	return b
}

// WithShareSizeGiB sets the ShareSizeGiB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShareSizeGiB field is set to the value of the last call.
func (b *AzureFilesConfigApplyConfiguration) WithShareSizeGiB(value int) *AzureFilesConfigApplyConfiguration {
	b.ShareSizeGiB = &value
	return b
}
