// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ChronicleStatusApplyConfiguration represents a declarative configuration of the ChronicleStatus type for use
// with apply.
type ChronicleStatusApplyConfiguration struct {
	Ready *bool `json:"ready,omitempty"`
}

// ChronicleStatusApplyConfiguration constructs a declarative configuration of the ChronicleStatus type for use with
// apply.
func ChronicleStatus() *ChronicleStatusApplyConfiguration {
	return &ChronicleStatusApplyConfiguration{}
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *ChronicleStatusApplyConfiguration) WithReady(value bool) *ChronicleStatusApplyConfiguration {
	b.Ready = &value
	return b
}
