// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ChronicleS3StorageConfigApplyConfiguration represents a declarative configuration of the ChronicleS3StorageConfig type for use
// with apply.
type ChronicleS3StorageConfigApplyConfiguration struct {
	Enabled *bool   `json:"Enabled,omitempty"`
	Bucket  *string `json:"Bucket,omitempty"`
	Region  *string `json:"Region,omitempty"`
	Prefix  *string `json:"Prefix,omitempty"`
}

// ChronicleS3StorageConfigApplyConfiguration constructs a declarative configuration of the ChronicleS3StorageConfig type for use with
// apply.
func ChronicleS3StorageConfig() *ChronicleS3StorageConfigApplyConfiguration {
	return &ChronicleS3StorageConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ChronicleS3StorageConfigApplyConfiguration) WithEnabled(value bool) *ChronicleS3StorageConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *ChronicleS3StorageConfigApplyConfiguration) WithBucket(value string) *ChronicleS3StorageConfigApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *ChronicleS3StorageConfigApplyConfiguration) WithRegion(value string) *ChronicleS3StorageConfigApplyConfiguration {
	b.Region = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *ChronicleS3StorageConfigApplyConfiguration) WithPrefix(value string) *ChronicleS3StorageConfigApplyConfiguration {
	b.Prefix = &value
	return b
}
