// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ChronicleMetricsConfigApplyConfiguration represents a declarative configuration of the ChronicleMetricsConfig type for use
// with apply.
type ChronicleMetricsConfigApplyConfiguration struct {
	Enabled *bool   `json:"Enabled,omitempty"`
	Listen  *string `json:"Listen,omitempty"`
}

// ChronicleMetricsConfigApplyConfiguration constructs a declarative configuration of the ChronicleMetricsConfig type for use with
// apply.
func ChronicleMetricsConfig() *ChronicleMetricsConfigApplyConfiguration {
	return &ChronicleMetricsConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ChronicleMetricsConfigApplyConfiguration) WithEnabled(value bool) *ChronicleMetricsConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithListen sets the Listen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listen field is set to the value of the last call.
func (b *ChronicleMetricsConfigApplyConfiguration) WithListen(value string) *ChronicleMetricsConfigApplyConfiguration {
	b.Listen = &value
	return b
}
