// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// ChronicleLoggingConfigApplyConfiguration represents a declarative configuration of the ChronicleLoggingConfig type for use
// with apply.
type ChronicleLoggingConfigApplyConfiguration struct {
	ServiceLog       *string                                `json:"ServiceLog,omitempty"`
	ServiceLogLevel  *corev1beta1.ChronicleServiceLogLevel  `json:"ServiceLogLevel,omitempty"`
	ServiceLogFormat *corev1beta1.ChronicleServiceLogFormat `json:"ServiceLogFormat,omitempty"`
}

// ChronicleLoggingConfigApplyConfiguration constructs a declarative configuration of the ChronicleLoggingConfig type for use with
// apply.
func ChronicleLoggingConfig() *ChronicleLoggingConfigApplyConfiguration {
	return &ChronicleLoggingConfigApplyConfiguration{}
}

// WithServiceLog sets the ServiceLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceLog field is set to the value of the last call.
func (b *ChronicleLoggingConfigApplyConfiguration) WithServiceLog(value string) *ChronicleLoggingConfigApplyConfiguration {
	b.ServiceLog = &value
	return b
}

// WithServiceLogLevel sets the ServiceLogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceLogLevel field is set to the value of the last call.
func (b *ChronicleLoggingConfigApplyConfiguration) WithServiceLogLevel(value corev1beta1.ChronicleServiceLogLevel) *ChronicleLoggingConfigApplyConfiguration {
	b.ServiceLogLevel = &value
	return b
}

// WithServiceLogFormat sets the ServiceLogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceLogFormat field is set to the value of the last call.
func (b *ChronicleLoggingConfigApplyConfiguration) WithServiceLogFormat(value corev1beta1.ChronicleServiceLogFormat) *ChronicleLoggingConfigApplyConfiguration {
	b.ServiceLogFormat = &value
	return b
}
