// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ChronicleConfigApplyConfiguration represents a declarative configuration of the ChronicleConfig type for use
// with apply.
type ChronicleConfigApplyConfiguration struct {
	Http         *ChronicleHttpConfigApplyConfiguration         `json:"Http,omitempty"`
	Metrics      *ChronicleMetricsConfigApplyConfiguration      `json:"Metrics,omitempty"`
	Profiling    *ChronicleProfilingConfigApplyConfiguration    `json:"Profiling,omitempty"`
	S3Storage    *ChronicleS3StorageConfigApplyConfiguration    `json:"S3Storage,omitempty"`
	LocalStorage *ChronicleLocalStorageConfigApplyConfiguration `json:"LocalStorage,omitempty"`
	Logging      *ChronicleLoggingConfigApplyConfiguration      `json:"Logging,omitempty"`
}

// ChronicleConfigApplyConfiguration constructs a declarative configuration of the ChronicleConfig type for use with
// apply.
func ChronicleConfig() *ChronicleConfigApplyConfiguration {
	return &ChronicleConfigApplyConfiguration{}
}

// WithHttp sets the Http field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http field is set to the value of the last call.
func (b *ChronicleConfigApplyConfiguration) WithHttp(value *ChronicleHttpConfigApplyConfiguration) *ChronicleConfigApplyConfiguration {
	b.Http = value
	return b
}

// WithMetrics sets the Metrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metrics field is set to the value of the last call.
func (b *ChronicleConfigApplyConfiguration) WithMetrics(value *ChronicleMetricsConfigApplyConfiguration) *ChronicleConfigApplyConfiguration {
	b.Metrics = value
	return b
}

// WithProfiling sets the Profiling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profiling field is set to the value of the last call.
func (b *ChronicleConfigApplyConfiguration) WithProfiling(value *ChronicleProfilingConfigApplyConfiguration) *ChronicleConfigApplyConfiguration {
	b.Profiling = value
	return b
}

// WithS3Storage sets the S3Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Storage field is set to the value of the last call.
func (b *ChronicleConfigApplyConfiguration) WithS3Storage(value *ChronicleS3StorageConfigApplyConfiguration) *ChronicleConfigApplyConfiguration {
	b.S3Storage = value
	return b
}

// WithLocalStorage sets the LocalStorage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalStorage field is set to the value of the last call.
func (b *ChronicleConfigApplyConfiguration) WithLocalStorage(value *ChronicleLocalStorageConfigApplyConfiguration) *ChronicleConfigApplyConfiguration {
	b.LocalStorage = value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *ChronicleConfigApplyConfiguration) WithLogging(value *ChronicleLoggingConfigApplyConfiguration) *ChronicleConfigApplyConfiguration {
	b.Logging = value
	return b
}
