// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ChronicleSpecApplyConfiguration represents a declarative configuration of the ChronicleSpec type for use
// with apply.
type ChronicleSpecApplyConfiguration struct {
	Config               *ChronicleConfigApplyConfiguration `json:"config,omitempty"`
	ImagePullSecrets     []string                           `json:"imagePullSecrets,omitempty"`
	NodeSelector         map[string]string                  `json:"nodeSelector,omitempty"`
	AddEnv               map[string]string                  `json:"addEnv,omitempty"`
	Image                *string                            `json:"image,omitempty"`
	AwsAccountId         *string                            `json:"awsAccountId,omitempty"`
	ClusterDate          *string                            `json:"clusterDate,omitempty"`
	WorkloadCompoundName *string                            `json:"workloadCompoundName,omitempty"`
}

// ChronicleSpecApplyConfiguration constructs a declarative configuration of the ChronicleSpec type for use with
// apply.
func ChronicleSpec() *ChronicleSpecApplyConfiguration {
	return &ChronicleSpecApplyConfiguration{}
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *ChronicleSpecApplyConfiguration) WithConfig(value *ChronicleConfigApplyConfiguration) *ChronicleSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *ChronicleSpecApplyConfiguration) WithImagePullSecrets(values ...string) *ChronicleSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *ChronicleSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *ChronicleSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithAddEnv puts the entries into the AddEnv field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AddEnv field,
// overwriting an existing map entries in AddEnv field with the same key.
func (b *ChronicleSpecApplyConfiguration) WithAddEnv(entries map[string]string) *ChronicleSpecApplyConfiguration {
	if b.AddEnv == nil && len(entries) > 0 {
		b.AddEnv = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AddEnv[k] = v
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ChronicleSpecApplyConfiguration) WithImage(value string) *ChronicleSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithAwsAccountId sets the AwsAccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AwsAccountId field is set to the value of the last call.
func (b *ChronicleSpecApplyConfiguration) WithAwsAccountId(value string) *ChronicleSpecApplyConfiguration {
	b.AwsAccountId = &value
	return b
}

// WithClusterDate sets the ClusterDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDate field is set to the value of the last call.
func (b *ChronicleSpecApplyConfiguration) WithClusterDate(value string) *ChronicleSpecApplyConfiguration {
	b.ClusterDate = &value
	return b
}

// WithWorkloadCompoundName sets the WorkloadCompoundName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadCompoundName field is set to the value of the last call.
func (b *ChronicleSpecApplyConfiguration) WithWorkloadCompoundName(value string) *ChronicleSpecApplyConfiguration {
	b.WorkloadCompoundName = &value
	return b
}
