// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// ConnectLoggingConfigApplyConfiguration represents a declarative configuration of the ConnectLoggingConfig type for use
// with apply.
type ConnectLoggingConfigApplyConfiguration struct {
	ServiceLog       *string                              `json:"ServiceLog,omitempty"`
	ServiceLogLevel  *string                              `json:"ServiceLogLevel,omitempty"`
	ServiceLogFormat *corev1beta1.ConnectServiceLogFormat `json:"ServiceLogFormat,omitempty"`
	AccessLog        *string                              `json:"AccessLog,omitempty"`
	AccessLogFormat  *corev1beta1.ConnectAccessLogFormat  `json:"AccessLogFormat,omitempty"`
	AuditLog         *string                              `json:"AuditLog,omitempty"`
	AuditLogFormat   *corev1beta1.ConnectServiceLogFormat `json:"AuditLogFormat,omitempty"`
}

// ConnectLoggingConfigApplyConfiguration constructs a declarative configuration of the ConnectLoggingConfig type for use with
// apply.
func ConnectLoggingConfig() *ConnectLoggingConfigApplyConfiguration {
	return &ConnectLoggingConfigApplyConfiguration{}
}

// WithServiceLog sets the ServiceLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceLog field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithServiceLog(value string) *ConnectLoggingConfigApplyConfiguration {
	b.ServiceLog = &value
	return b
}

// WithServiceLogLevel sets the ServiceLogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceLogLevel field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithServiceLogLevel(value string) *ConnectLoggingConfigApplyConfiguration {
	b.ServiceLogLevel = &value
	return b
}

// WithServiceLogFormat sets the ServiceLogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceLogFormat field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithServiceLogFormat(value corev1beta1.ConnectServiceLogFormat) *ConnectLoggingConfigApplyConfiguration {
	b.ServiceLogFormat = &value
	return b
}

// WithAccessLog sets the AccessLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessLog field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithAccessLog(value string) *ConnectLoggingConfigApplyConfiguration {
	b.AccessLog = &value
	return b
}

// WithAccessLogFormat sets the AccessLogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessLogFormat field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithAccessLogFormat(value corev1beta1.ConnectAccessLogFormat) *ConnectLoggingConfigApplyConfiguration {
	b.AccessLogFormat = &value
	return b
}

// WithAuditLog sets the AuditLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuditLog field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithAuditLog(value string) *ConnectLoggingConfigApplyConfiguration {
	b.AuditLog = &value
	return b
}

// WithAuditLogFormat sets the AuditLogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuditLogFormat field is set to the value of the last call.
func (b *ConnectLoggingConfigApplyConfiguration) WithAuditLogFormat(value corev1beta1.ConnectServiceLogFormat) *ConnectLoggingConfigApplyConfiguration {
	b.AuditLogFormat = &value
	return b
}
