// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectApplicationsConfigApplyConfiguration represents a declarative configuration of the ConnectApplicationsConfig type for use
// with apply.
type ConnectApplicationsConfigApplyConfiguration struct {
	BundleRetentionLimit     *int  `json:"BundleRetentionLimit,omitempty"`
	PythonEnvironmentReaping *bool `json:"PythonEnvironmentReaping,omitempty"`
	OAuthIntegrationsEnabled *bool `json:"OAuthIntegrationsEnabled,omitempty"`
	ScheduleConcurrency      *int  `json:"ScheduleConcurrency,omitempty"`
}

// ConnectApplicationsConfigApplyConfiguration constructs a declarative configuration of the ConnectApplicationsConfig type for use with
// apply.
func ConnectApplicationsConfig() *ConnectApplicationsConfigApplyConfiguration {
	return &ConnectApplicationsConfigApplyConfiguration{}
}

// WithBundleRetentionLimit sets the BundleRetentionLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BundleRetentionLimit field is set to the value of the last call.
func (b *ConnectApplicationsConfigApplyConfiguration) WithBundleRetentionLimit(value int) *ConnectApplicationsConfigApplyConfiguration {
	b.BundleRetentionLimit = &value
	return b
}

// WithPythonEnvironmentReaping sets the PythonEnvironmentReaping field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PythonEnvironmentReaping field is set to the value of the last call.
func (b *ConnectApplicationsConfigApplyConfiguration) WithPythonEnvironmentReaping(value bool) *ConnectApplicationsConfigApplyConfiguration {
	b.PythonEnvironmentReaping = &value
	return b
}

// WithOAuthIntegrationsEnabled sets the OAuthIntegrationsEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OAuthIntegrationsEnabled field is set to the value of the last call.
func (b *ConnectApplicationsConfigApplyConfiguration) WithOAuthIntegrationsEnabled(value bool) *ConnectApplicationsConfigApplyConfiguration {
	b.OAuthIntegrationsEnabled = &value
	return b
}

// WithScheduleConcurrency sets the ScheduleConcurrency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScheduleConcurrency field is set to the value of the last call.
func (b *ConnectApplicationsConfigApplyConfiguration) WithScheduleConcurrency(value int) *ConnectApplicationsConfigApplyConfiguration {
	b.ScheduleConcurrency = &value
	return b
}
