// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectSamlConfigApplyConfiguration represents a declarative configuration of the ConnectSamlConfig type for use
// with apply.
type ConnectSamlConfigApplyConfiguration struct {
	IdPMetaDataURL      *string `json:"IdPMetaDataURL,omitempty"`
	IdPAttributeProfile *string `json:"IdPAttributeProfile,omitempty"`
	UsernameAttribute   *string `json:"UsernameAttribute,omitempty"`
	FirstNameAttribute  *string `json:"FirstNameAttribute,omitempty"`
	LastNameAttribute   *string `json:"LastNameAttribute,omitempty"`
	EmailAttribute      *string `json:"EmailAttribute,omitempty"`
}

// ConnectSamlConfigApplyConfiguration constructs a declarative configuration of the ConnectSamlConfig type for use with
// apply.
func ConnectSamlConfig() *ConnectSamlConfigApplyConfiguration {
	return &ConnectSamlConfigApplyConfiguration{}
}

// WithIdPMetaDataURL sets the IdPMetaDataURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdPMetaDataURL field is set to the value of the last call.
func (b *ConnectSamlConfigApplyConfiguration) WithIdPMetaDataURL(value string) *ConnectSamlConfigApplyConfiguration {
	b.IdPMetaDataURL = &value
	return b
}

// WithIdPAttributeProfile sets the IdPAttributeProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdPAttributeProfile field is set to the value of the last call.
func (b *ConnectSamlConfigApplyConfiguration) WithIdPAttributeProfile(value string) *ConnectSamlConfigApplyConfiguration {
	b.IdPAttributeProfile = &value
	return b
}

// WithUsernameAttribute sets the UsernameAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsernameAttribute field is set to the value of the last call.
func (b *ConnectSamlConfigApplyConfiguration) WithUsernameAttribute(value string) *ConnectSamlConfigApplyConfiguration {
	b.UsernameAttribute = &value
	return b
}

// WithFirstNameAttribute sets the FirstNameAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirstNameAttribute field is set to the value of the last call.
func (b *ConnectSamlConfigApplyConfiguration) WithFirstNameAttribute(value string) *ConnectSamlConfigApplyConfiguration {
	b.FirstNameAttribute = &value
	return b
}

// WithLastNameAttribute sets the LastNameAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastNameAttribute field is set to the value of the last call.
func (b *ConnectSamlConfigApplyConfiguration) WithLastNameAttribute(value string) *ConnectSamlConfigApplyConfiguration {
	b.LastNameAttribute = &value
	return b
}

// WithEmailAttribute sets the EmailAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailAttribute field is set to the value of the last call.
func (b *ConnectSamlConfigApplyConfiguration) WithEmailAttribute(value string) *ConnectSamlConfigApplyConfiguration {
	b.EmailAttribute = &value
	return b
}
