// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectOAuth2ConfigApplyConfiguration represents a declarative configuration of the ConnectOAuth2Config type for use
// with apply.
type ConnectOAuth2ConfigApplyConfiguration struct {
	ClientId             *string  `json:"ClientId,omitempty"`
	ClientSecretFile     *string  `json:"ClientSecretFile,omitempty"`
	OpenIDConnectIssuer  *string  `json:"OpenIDConnectIssuer,omitempty"`
	RequireUsernameClaim *bool    `json:"RequireUsernameClaim,omitempty"`
	CustomScope          []string `json:"CustomScope,omitempty"`
	GroupsAutoProvision  *bool    `json:"GroupsAutoProvision,omitempty"`
	UniqueIdClaim        *string  `json:"UniqueIdClaim,omitempty"`
	EmailClaim           *string  `json:"EmailClaim,omitempty"`
	UsernameClaim        *string  `json:"UsernameClaim,omitempty"`
	GroupsClaim          *string  `json:"GroupsClaim,omitempty"`
	Logging              *bool    `json:"Logging,omitempty"`
}

// ConnectOAuth2ConfigApplyConfiguration constructs a declarative configuration of the ConnectOAuth2Config type for use with
// apply.
func ConnectOAuth2Config() *ConnectOAuth2ConfigApplyConfiguration {
	return &ConnectOAuth2ConfigApplyConfiguration{}
}

// WithClientId sets the ClientId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientId field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithClientId(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.ClientId = &value
	return b
}

// WithClientSecretFile sets the ClientSecretFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecretFile field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithClientSecretFile(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.ClientSecretFile = &value
	return b
}

// WithOpenIDConnectIssuer sets the OpenIDConnectIssuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenIDConnectIssuer field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithOpenIDConnectIssuer(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.OpenIDConnectIssuer = &value
	return b
}

// WithRequireUsernameClaim sets the RequireUsernameClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireUsernameClaim field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithRequireUsernameClaim(value bool) *ConnectOAuth2ConfigApplyConfiguration {
	b.RequireUsernameClaim = &value
	return b
}

// WithCustomScope adds the given value to the CustomScope field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomScope field.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithCustomScope(values ...string) *ConnectOAuth2ConfigApplyConfiguration {
	for i := range values {
		b.CustomScope = append(b.CustomScope, values[i])
	}
	return b
}

// WithGroupsAutoProvision sets the GroupsAutoProvision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupsAutoProvision field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithGroupsAutoProvision(value bool) *ConnectOAuth2ConfigApplyConfiguration {
	b.GroupsAutoProvision = &value
	return b
}

// WithUniqueIdClaim sets the UniqueIdClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UniqueIdClaim field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithUniqueIdClaim(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.UniqueIdClaim = &value
	return b
}

// WithEmailClaim sets the EmailClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailClaim field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithEmailClaim(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.EmailClaim = &value
	return b
}

// WithUsernameClaim sets the UsernameClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsernameClaim field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithUsernameClaim(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.UsernameClaim = &value
	return b
}

// WithGroupsClaim sets the GroupsClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupsClaim field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithGroupsClaim(value string) *ConnectOAuth2ConfigApplyConfiguration {
	b.GroupsClaim = &value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *ConnectOAuth2ConfigApplyConfiguration) WithLogging(value bool) *ConnectOAuth2ConfigApplyConfiguration {
	b.Logging = &value
	return b
}
