// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectPythonConfigApplyConfiguration represents a declarative configuration of the ConnectPythonConfig type for use
// with apply.
type ConnectPythonConfigApplyConfiguration struct {
	Enabled *bool `json:"Enabled,omitempty"`
}

// ConnectPythonConfigApplyConfiguration constructs a declarative configuration of the ConnectPythonConfig type for use with
// apply.
func ConnectPythonConfig() *ConnectPythonConfigApplyConfiguration {
	return &ConnectPythonConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ConnectPythonConfigApplyConfiguration) WithEnabled(value bool) *ConnectPythonConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
