// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectConfigApplyConfiguration represents a declarative configuration of the ConnectConfig type for use
// with apply.
type ConnectConfigApplyConfiguration struct {
	Server             *ConnectServerConfigApplyConfiguration                `json:"Server,omitempty"`
	Http               *ConnectHttpConfigApplyConfiguration                  `json:"Http,omitempty"`
	Metrics            *ConnectMetricsConfigApplyConfiguration               `json:"Metrics,omitempty"`
	Database           *ConnectDatabaseConfigApplyConfiguration              `json:"Database,omitempty"`
	Postgres           *ConnectPostgresConfigApplyConfiguration              `json:"Postgres,omitempty"`
	Logging            *ConnectLoggingConfigApplyConfiguration               `json:"Logging,omitempty"`
	Launcher           *ConnectLauncherConfigApplyConfiguration              `json:"Launcher,omitempty"`
	Authentication     *ConnectAuthenticationConfigApplyConfiguration        `json:"Authentication,omitempty"`
	Authorization      *ConnectAuthorizationConfigApplyConfiguration         `json:"Authorization,omitempty"`
	Applications       *ConnectApplicationsConfigApplyConfiguration          `json:"Applications,omitempty"`
	OAuth2             *ConnectOAuth2ConfigApplyConfiguration                `json:"OAuth2,omitempty"`
	R                  *ConnectRConfigApplyConfiguration                     `json:"R,omitempty"`
	Python             *ConnectPythonConfigApplyConfiguration                `json:"Python,omitempty"`
	Quarto             *ConnectQuartoConfigApplyConfiguration                `json:"Quarto,omitempty"`
	SAML               *ConnectSamlConfigApplyConfiguration                  `json:"SAML,omitempty"`
	Scheduler          *ConnectSchedulerConfigApplyConfiguration             `json:"Scheduler,omitempty"`
	RPackageRepository map[string]RPackageRepositoryConfigApplyConfiguration `json:"RPackageRepositories,omitempty"`
	TableauIntegration *ConnectTableauIntegrationConfigApplyConfiguration    `json:"TableauIntegration,omitempty"`
}

// ConnectConfigApplyConfiguration constructs a declarative configuration of the ConnectConfig type for use with
// apply.
func ConnectConfig() *ConnectConfigApplyConfiguration {
	return &ConnectConfigApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithServer(value *ConnectServerConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Server = value
	return b
}

// WithHttp sets the Http field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithHttp(value *ConnectHttpConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Http = value
	return b
}

// WithMetrics sets the Metrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metrics field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithMetrics(value *ConnectMetricsConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Metrics = value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithDatabase(value *ConnectDatabaseConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Database = value
	return b
}

// WithPostgres sets the Postgres field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Postgres field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithPostgres(value *ConnectPostgresConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Postgres = value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithLogging(value *ConnectLoggingConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Logging = value
	return b
}

// WithLauncher sets the Launcher field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Launcher field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithLauncher(value *ConnectLauncherConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Launcher = value
	return b
}

// WithAuthentication sets the Authentication field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authentication field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithAuthentication(value *ConnectAuthenticationConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Authentication = value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithAuthorization(value *ConnectAuthorizationConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Authorization = value
	return b
}

// WithApplications sets the Applications field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Applications field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithApplications(value *ConnectApplicationsConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Applications = value
	return b
}

// WithOAuth2 sets the OAuth2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OAuth2 field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithOAuth2(value *ConnectOAuth2ConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.OAuth2 = value
	return b
}

// WithR sets the R field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the R field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithR(value *ConnectRConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.R = value
	return b
}

// WithPython sets the Python field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Python field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithPython(value *ConnectPythonConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Python = value
	return b
}

// WithQuarto sets the Quarto field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quarto field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithQuarto(value *ConnectQuartoConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Quarto = value
	return b
}

// WithSAML sets the SAML field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SAML field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithSAML(value *ConnectSamlConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.SAML = value
	return b
}

// WithScheduler sets the Scheduler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheduler field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithScheduler(value *ConnectSchedulerConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.Scheduler = value
	return b
}

// WithRPackageRepository puts the entries into the RPackageRepository field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RPackageRepository field,
// overwriting an existing map entries in RPackageRepository field with the same key.
func (b *ConnectConfigApplyConfiguration) WithRPackageRepository(entries map[string]RPackageRepositoryConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	if b.RPackageRepository == nil && len(entries) > 0 {
		b.RPackageRepository = make(map[string]RPackageRepositoryConfigApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.RPackageRepository[k] = v
	}
	return b
}

// WithTableauIntegration sets the TableauIntegration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TableauIntegration field is set to the value of the last call.
func (b *ConnectConfigApplyConfiguration) WithTableauIntegration(value *ConnectTableauIntegrationConfigApplyConfiguration) *ConnectConfigApplyConfiguration {
	b.TableauIntegration = value
	return b
}
