// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectTableauIntegrationConfigApplyConfiguration represents a declarative configuration of the ConnectTableauIntegrationConfig type for use
// with apply.
type ConnectTableauIntegrationConfigApplyConfiguration struct {
	Logging *bool `json:"Logging,omitempty"`
}

// ConnectTableauIntegrationConfigApplyConfiguration constructs a declarative configuration of the ConnectTableauIntegrationConfig type for use with
// apply.
func ConnectTableauIntegrationConfig() *ConnectTableauIntegrationConfigApplyConfiguration {
	return &ConnectTableauIntegrationConfigApplyConfiguration{}
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *ConnectTableauIntegrationConfigApplyConfiguration) WithLogging(value bool) *ConnectTableauIntegrationConfigApplyConfiguration {
	b.Logging = &value
	return b
}
