// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectLauncherConfigApplyConfiguration represents a declarative configuration of the ConnectLauncherConfig type for use
// with apply.
type ConnectLauncherConfigApplyConfiguration struct {
	Enabled                  *bool    `json:"Enabled,omitempty"`
	Kubernetes               *bool    `json:"Kubernetes,omitempty"`
	ClusterDefinition        []string `json:"ClusterDefinition,omitempty"`
	KubernetesNamespace      *string  `json:"KubernetesNamespace,omitempty"`
	KubernetesProfilesConfig *string  `json:"KubernetesProfilesConfig,omitempty"`
	DataDirPVCName           *string  `json:"DataDirPVCName,omitempty"`
	KubernetesUseTemplates   *bool    `json:"KubernetesUseTemplates,omitempty"`
	ScratchPath              *string  `json:"ScratchPath,omitempty"`
}

// ConnectLauncherConfigApplyConfiguration constructs a declarative configuration of the ConnectLauncherConfig type for use with
// apply.
func ConnectLauncherConfig() *ConnectLauncherConfigApplyConfiguration {
	return &ConnectLauncherConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithEnabled(value bool) *ConnectLauncherConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithKubernetes(value bool) *ConnectLauncherConfigApplyConfiguration {
	b.Kubernetes = &value
	return b
}

// WithClusterDefinition adds the given value to the ClusterDefinition field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterDefinition field.
func (b *ConnectLauncherConfigApplyConfiguration) WithClusterDefinition(values ...string) *ConnectLauncherConfigApplyConfiguration {
	for i := range values {
		b.ClusterDefinition = append(b.ClusterDefinition, values[i])
	}
	return b
}

// WithKubernetesNamespace sets the KubernetesNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubernetesNamespace field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithKubernetesNamespace(value string) *ConnectLauncherConfigApplyConfiguration {
	b.KubernetesNamespace = &value
	return b
}

// WithKubernetesProfilesConfig sets the KubernetesProfilesConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubernetesProfilesConfig field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithKubernetesProfilesConfig(value string) *ConnectLauncherConfigApplyConfiguration {
	b.KubernetesProfilesConfig = &value
	return b
}

// WithDataDirPVCName sets the DataDirPVCName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDirPVCName field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithDataDirPVCName(value string) *ConnectLauncherConfigApplyConfiguration {
	b.DataDirPVCName = &value
	return b
}

// WithKubernetesUseTemplates sets the KubernetesUseTemplates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubernetesUseTemplates field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithKubernetesUseTemplates(value bool) *ConnectLauncherConfigApplyConfiguration {
	b.KubernetesUseTemplates = &value
	return b
}

// WithScratchPath sets the ScratchPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScratchPath field is set to the value of the last call.
func (b *ConnectLauncherConfigApplyConfiguration) WithScratchPath(value string) *ConnectLauncherConfigApplyConfiguration {
	b.ScratchPath = &value
	return b
}
