// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectRuntimeImageSpecApplyConfiguration represents a declarative configuration of the ConnectRuntimeImageSpec type for use
// with apply.
type ConnectRuntimeImageSpecApplyConfiguration struct {
	RVersion      *string `json:"rVersion,omitempty"`
	PyVersion     *string `json:"pyVersion,omitempty"`
	OSVersion     *string `json:"osVersion,omitempty"`
	QuartoVersion *string `json:"quartoVersion,omitempty"`
	Repo          *string `json:"repo,omitempty"`
}

// ConnectRuntimeImageSpecApplyConfiguration constructs a declarative configuration of the ConnectRuntimeImageSpec type for use with
// apply.
func ConnectRuntimeImageSpec() *ConnectRuntimeImageSpecApplyConfiguration {
	return &ConnectRuntimeImageSpecApplyConfiguration{}
}

// WithRVersion sets the RVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RVersion field is set to the value of the last call.
func (b *ConnectRuntimeImageSpecApplyConfiguration) WithRVersion(value string) *ConnectRuntimeImageSpecApplyConfiguration {
	b.RVersion = &value
	return b
}

// WithPyVersion sets the PyVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PyVersion field is set to the value of the last call.
func (b *ConnectRuntimeImageSpecApplyConfiguration) WithPyVersion(value string) *ConnectRuntimeImageSpecApplyConfiguration {
	b.PyVersion = &value
	return b
}

// WithOSVersion sets the OSVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OSVersion field is set to the value of the last call.
func (b *ConnectRuntimeImageSpecApplyConfiguration) WithOSVersion(value string) *ConnectRuntimeImageSpecApplyConfiguration {
	b.OSVersion = &value
	return b
}

// WithQuartoVersion sets the QuartoVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuartoVersion field is set to the value of the last call.
func (b *ConnectRuntimeImageSpecApplyConfiguration) WithQuartoVersion(value string) *ConnectRuntimeImageSpecApplyConfiguration {
	b.QuartoVersion = &value
	return b
}

// WithRepo sets the Repo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repo field is set to the value of the last call.
func (b *ConnectRuntimeImageSpecApplyConfiguration) WithRepo(value string) *ConnectRuntimeImageSpecApplyConfiguration {
	b.Repo = &value
	return b
}
