// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectPostgresConfigApplyConfiguration represents a declarative configuration of the ConnectPostgresConfig type for use
// with apply.
type ConnectPostgresConfigApplyConfiguration struct {
	URL                *string `json:"URL,omitempty"`
	InstrumentationURL *string `json:"InstrumentationURL,omitempty"`
}

// ConnectPostgresConfigApplyConfiguration constructs a declarative configuration of the ConnectPostgresConfig type for use with
// apply.
func ConnectPostgresConfig() *ConnectPostgresConfigApplyConfiguration {
	return &ConnectPostgresConfigApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *ConnectPostgresConfigApplyConfiguration) WithURL(value string) *ConnectPostgresConfigApplyConfiguration {
	b.URL = &value
	return b
}

// WithInstrumentationURL sets the InstrumentationURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstrumentationURL field is set to the value of the last call.
func (b *ConnectPostgresConfigApplyConfiguration) WithInstrumentationURL(value string) *ConnectPostgresConfigApplyConfiguration {
	b.InstrumentationURL = &value
	return b
}
