// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ConnectStatusApplyConfiguration represents a declarative configuration of the ConnectStatus type for use
// with apply.
type ConnectStatusApplyConfiguration struct {
	CommonProductStatusApplyConfiguration `json:",inline"`
	KeySecretRef                          *v1.SecretReference `json:"keySecretRef,omitempty"`
	Ready                                 *bool               `json:"ready,omitempty"`
}

// ConnectStatusApplyConfiguration constructs a declarative configuration of the ConnectStatus type for use with
// apply.
func ConnectStatus() *ConnectStatusApplyConfiguration {
	return &ConnectStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ConnectStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ConnectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.CommonProductStatusApplyConfiguration.Conditions = append(b.CommonProductStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ConnectStatusApplyConfiguration) WithObservedGeneration(value int64) *ConnectStatusApplyConfiguration {
	b.CommonProductStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ConnectStatusApplyConfiguration) WithVersion(value string) *ConnectStatusApplyConfiguration {
	b.CommonProductStatusApplyConfiguration.Version = &value
	return b
}

// WithKeySecretRef sets the KeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeySecretRef field is set to the value of the last call.
func (b *ConnectStatusApplyConfiguration) WithKeySecretRef(value v1.SecretReference) *ConnectStatusApplyConfiguration {
	b.KeySecretRef = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *ConnectStatusApplyConfiguration) WithReady(value bool) *ConnectStatusApplyConfiguration {
	b.Ready = &value
	return b
}
