// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// ConnectRConfigApplyConfiguration represents a declarative configuration of the ConnectRConfig type for use
// with apply.
type ConnectRConfigApplyConfiguration struct {
	Enabled                         *bool                                        `json:"Enabled,omitempty"`
	PositPackageManagerURLRewriting *corev1beta1.ConnectPackageManagerUrlRewrite `json:"PositPackageManagerURLRewriting,omitempty"`
}

// ConnectRConfigApplyConfiguration constructs a declarative configuration of the ConnectRConfig type for use with
// apply.
func ConnectRConfig() *ConnectRConfigApplyConfiguration {
	return &ConnectRConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ConnectRConfigApplyConfiguration) WithEnabled(value bool) *ConnectRConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithPositPackageManagerURLRewriting sets the PositPackageManagerURLRewriting field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PositPackageManagerURLRewriting field is set to the value of the last call.
func (b *ConnectRConfigApplyConfiguration) WithPositPackageManagerURLRewriting(value corev1beta1.ConnectPackageManagerUrlRewrite) *ConnectRConfigApplyConfiguration {
	b.PositPackageManagerURLRewriting = &value
	return b
}
