// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// ConnectServerConfigApplyConfiguration represents a declarative configuration of the ConnectServerConfig type for use
// with apply.
type ConnectServerConfigApplyConfiguration struct {
	Address                *string                      `json:"Address,omitempty"`
	DataDir                *string                      `json:"DataDir,omitempty"`
	FrameOptionsContent    *string                      `json:"FrameOptionsContent,omitempty"`
	FrameOptionsDashboard  *string                      `json:"FrameOptionsDashboard,omitempty"`
	DefaultContentListView *corev1beta1.ContentListView `json:"DefaultContentListView,omitempty"`
	LoggedInWarning        *string                      `json:"LoggedInWarning,omitempty"`
	PublicWarning          *string                      `json:"PublicWarning,omitempty"`
	ProxyHeaderLogging     *bool                        `json:"ProxyHeaderLogging,omitempty"`
	EmailProvider          *string                      `json:"EmailProvider,omitempty"`
	SenderEmail            *string                      `json:"SenderEmail,omitempty"`
	SenderEmailDisplayName *string                      `json:"SenderEmailDisplayName,omitempty"`
	EmailTo                *string                      `json:"EmailTo,omitempty"`
	HideEmailAddresses     *bool                        `json:"HideEmailAddresses,omitempty"`
}

// ConnectServerConfigApplyConfiguration constructs a declarative configuration of the ConnectServerConfig type for use with
// apply.
func ConnectServerConfig() *ConnectServerConfigApplyConfiguration {
	return &ConnectServerConfigApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithAddress(value string) *ConnectServerConfigApplyConfiguration {
	b.Address = &value
	return b
}

// WithDataDir sets the DataDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDir field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithDataDir(value string) *ConnectServerConfigApplyConfiguration {
	b.DataDir = &value
	return b
}

// WithFrameOptionsContent sets the FrameOptionsContent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FrameOptionsContent field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithFrameOptionsContent(value string) *ConnectServerConfigApplyConfiguration {
	b.FrameOptionsContent = &value
	return b
}

// WithFrameOptionsDashboard sets the FrameOptionsDashboard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FrameOptionsDashboard field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithFrameOptionsDashboard(value string) *ConnectServerConfigApplyConfiguration {
	b.FrameOptionsDashboard = &value
	return b
}

// WithDefaultContentListView sets the DefaultContentListView field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultContentListView field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithDefaultContentListView(value corev1beta1.ContentListView) *ConnectServerConfigApplyConfiguration {
	b.DefaultContentListView = &value
	return b
}

// WithLoggedInWarning sets the LoggedInWarning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoggedInWarning field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithLoggedInWarning(value string) *ConnectServerConfigApplyConfiguration {
	b.LoggedInWarning = &value
	return b
}

// WithPublicWarning sets the PublicWarning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicWarning field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithPublicWarning(value string) *ConnectServerConfigApplyConfiguration {
	b.PublicWarning = &value
	return b
}

// WithProxyHeaderLogging sets the ProxyHeaderLogging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyHeaderLogging field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithProxyHeaderLogging(value bool) *ConnectServerConfigApplyConfiguration {
	b.ProxyHeaderLogging = &value
	return b
}

// WithEmailProvider sets the EmailProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailProvider field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithEmailProvider(value string) *ConnectServerConfigApplyConfiguration {
	b.EmailProvider = &value
	return b
}

// WithSenderEmail sets the SenderEmail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SenderEmail field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithSenderEmail(value string) *ConnectServerConfigApplyConfiguration {
	b.SenderEmail = &value
	return b
}

// WithSenderEmailDisplayName sets the SenderEmailDisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SenderEmailDisplayName field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithSenderEmailDisplayName(value string) *ConnectServerConfigApplyConfiguration {
	b.SenderEmailDisplayName = &value
	return b
}

// WithEmailTo sets the EmailTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailTo field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithEmailTo(value string) *ConnectServerConfigApplyConfiguration {
	b.EmailTo = &value
	return b
}

// WithHideEmailAddresses sets the HideEmailAddresses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HideEmailAddresses field is set to the value of the last call.
func (b *ConnectServerConfigApplyConfiguration) WithHideEmailAddresses(value bool) *ConnectServerConfigApplyConfiguration {
	b.HideEmailAddresses = &value
	return b
}
