// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectSchedulerConfigApplyConfiguration represents a declarative configuration of the ConnectSchedulerConfig type for use
// with apply.
type ConnectSchedulerConfigApplyConfiguration struct {
	MaxCPURequest     *int `json:"MaxCPURequest,omitempty"`
	MaxCPULimit       *int `json:"MaxCPULimit,omitempty"`
	MaxMemoryRequest  *int `json:"MaxMemoryRequest,omitempty"`
	MaxMemoryLimit    *int `json:"MaxMemoryLimit,omitempty"`
	NvidiaGPULimit    *int `json:"NvidiaGPULimit,omitempty"`
	MaxNvidiaGPULimit *int `json:"MaxNvidiaGPULimit,omitempty"`
	AMDGPULimit       *int `json:"AMDGPULimit,omitempty"`
	MaxAMDGPULimit    *int `json:"MaxAMDGPULimit,omitempty"`
}

// ConnectSchedulerConfigApplyConfiguration constructs a declarative configuration of the ConnectSchedulerConfig type for use with
// apply.
func ConnectSchedulerConfig() *ConnectSchedulerConfigApplyConfiguration {
	return &ConnectSchedulerConfigApplyConfiguration{}
}

// WithMaxCPURequest sets the MaxCPURequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCPURequest field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithMaxCPURequest(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.MaxCPURequest = &value
	return b
}

// WithMaxCPULimit sets the MaxCPULimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCPULimit field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithMaxCPULimit(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.MaxCPULimit = &value
	return b
}

// WithMaxMemoryRequest sets the MaxMemoryRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMemoryRequest field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithMaxMemoryRequest(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.MaxMemoryRequest = &value
	return b
}

// WithMaxMemoryLimit sets the MaxMemoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMemoryLimit field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithMaxMemoryLimit(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.MaxMemoryLimit = &value
	return b
}

// WithNvidiaGPULimit sets the NvidiaGPULimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NvidiaGPULimit field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithNvidiaGPULimit(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.NvidiaGPULimit = &value
	return b
}

// WithMaxNvidiaGPULimit sets the MaxNvidiaGPULimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxNvidiaGPULimit field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithMaxNvidiaGPULimit(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.MaxNvidiaGPULimit = &value
	return b
}

// WithAMDGPULimit sets the AMDGPULimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AMDGPULimit field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithAMDGPULimit(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.AMDGPULimit = &value
	return b
}

// WithMaxAMDGPULimit sets the MaxAMDGPULimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAMDGPULimit field is set to the value of the last call.
func (b *ConnectSchedulerConfigApplyConfiguration) WithMaxAMDGPULimit(value int) *ConnectSchedulerConfigApplyConfiguration {
	b.MaxAMDGPULimit = &value
	return b
}
