// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// ConnectAuthenticationConfigApplyConfiguration represents a declarative configuration of the ConnectAuthenticationConfig type for use
// with apply.
type ConnectAuthenticationConfigApplyConfiguration struct {
	Provider *corev1beta1.AuthType `json:"Provider,omitempty"`
}

// ConnectAuthenticationConfigApplyConfiguration constructs a declarative configuration of the ConnectAuthenticationConfig type for use with
// apply.
func ConnectAuthenticationConfig() *ConnectAuthenticationConfigApplyConfiguration {
	return &ConnectAuthenticationConfigApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *ConnectAuthenticationConfigApplyConfiguration) WithProvider(value corev1beta1.AuthType) *ConnectAuthenticationConfigApplyConfiguration {
	b.Provider = &value
	return b
}
