// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ConnectQuartoConfigApplyConfiguration represents a declarative configuration of the ConnectQuartoConfig type for use
// with apply.
type ConnectQuartoConfigApplyConfiguration struct {
	Enabled *bool `json:"Enabled,omitempty"`
}

// ConnectQuartoConfigApplyConfiguration constructs a declarative configuration of the ConnectQuartoConfig type for use with
// apply.
func ConnectQuartoConfig() *ConnectQuartoConfigApplyConfiguration {
	return &ConnectQuartoConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ConnectQuartoConfigApplyConfiguration) WithEnabled(value bool) *ConnectQuartoConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
