// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// DatabaseSettingsApplyConfiguration represents a declarative configuration of the DatabaseSettings type for use
// with apply.
type DatabaseSettingsApplyConfiguration struct {
	Schema                *string `json:"schema,omitempty"`
	InstrumentationSchema *string `json:"instrumentationSchema,omitempty"`
}

// DatabaseSettingsApplyConfiguration constructs a declarative configuration of the DatabaseSettings type for use with
// apply.
func DatabaseSettings() *DatabaseSettingsApplyConfiguration {
	return &DatabaseSettingsApplyConfiguration{}
}

// WithSchema sets the Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schema field is set to the value of the last call.
func (b *DatabaseSettingsApplyConfiguration) WithSchema(value string) *DatabaseSettingsApplyConfiguration {
	b.Schema = &value
	return b
}

// WithInstrumentationSchema sets the InstrumentationSchema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstrumentationSchema field is set to the value of the last call.
func (b *DatabaseSettingsApplyConfiguration) WithInstrumentationSchema(value string) *DatabaseSettingsApplyConfiguration {
	b.InstrumentationSchema = &value
	return b
}
