// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// DatabricksConfigApplyConfiguration represents a declarative configuration of the DatabricksConfig type for use
// with apply.
type DatabricksConfigApplyConfiguration struct {
	Name     *string `json:"name,omitempty"`
	Url      *string `json:"url,omitempty"`
	ClientId *string `json:"clientId,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
}

// DatabricksConfigApplyConfiguration constructs a declarative configuration of the DatabricksConfig type for use with
// apply.
func DatabricksConfig() *DatabricksConfigApplyConfiguration {
	return &DatabricksConfigApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DatabricksConfigApplyConfiguration) WithName(value string) *DatabricksConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *DatabricksConfigApplyConfiguration) WithUrl(value string) *DatabricksConfigApplyConfiguration {
	b.Url = &value
	return b
}

// WithClientId sets the ClientId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientId field is set to the value of the last call.
func (b *DatabricksConfigApplyConfiguration) WithClientId(value string) *DatabricksConfigApplyConfiguration {
	b.ClientId = &value
	return b
}

// WithTenantId sets the TenantId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantId field is set to the value of the last call.
func (b *DatabricksConfigApplyConfiguration) WithTenantId(value string) *DatabricksConfigApplyConfiguration {
	b.TenantId = &value
	return b
}
