// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// FeatureEnablerConfigApplyConfiguration represents a declarative configuration of the FeatureEnablerConfig type for use
// with apply.
type FeatureEnablerConfigApplyConfiguration struct {
	ShowConfig  *bool `json:"showConfig,omitempty"`
	ShowAcademy *bool `json:"showAcademy,omitempty"`
}

// FeatureEnablerConfigApplyConfiguration constructs a declarative configuration of the FeatureEnablerConfig type for use with
// apply.
func FeatureEnablerConfig() *FeatureEnablerConfigApplyConfiguration {
	return &FeatureEnablerConfigApplyConfiguration{}
}

// WithShowConfig sets the ShowConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShowConfig field is set to the value of the last call.
func (b *FeatureEnablerConfigApplyConfiguration) WithShowConfig(value bool) *FeatureEnablerConfigApplyConfiguration {
	b.ShowConfig = &value
	return b
}

// WithShowAcademy sets the ShowAcademy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShowAcademy field is set to the value of the last call.
func (b *FeatureEnablerConfigApplyConfiguration) WithShowAcademy(value bool) *FeatureEnablerConfigApplyConfiguration {
	b.ShowAcademy = &value
	return b
}
