// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// FlightdeckSpecApplyConfiguration represents a declarative configuration of the FlightdeckSpec type for use
// with apply.
type FlightdeckSpecApplyConfiguration struct {
	SiteName             *string                                 `json:"siteName,omitempty"`
	Image                *string                                 `json:"image,omitempty"`
	ImagePullPolicy      *v1.PullPolicy                          `json:"imagePullPolicy,omitempty"`
	Port                 *int32                                  `json:"port,omitempty"`
	Replicas             *int                                    `json:"replicas,omitempty"`
	FeatureEnabler       *FeatureEnablerConfigApplyConfiguration `json:"featureEnabler,omitempty"`
	Domain               *string                                 `json:"domain,omitempty"`
	IngressClass         *string                                 `json:"ingressClass,omitempty"`
	IngressAnnotations   map[string]string                       `json:"ingressAnnotations,omitempty"`
	ImagePullSecrets     []string                                `json:"imagePullSecrets,omitempty"`
	AwsAccountId         *string                                 `json:"awsAccountId,omitempty"`
	ClusterDate          *string                                 `json:"clusterDate,omitempty"`
	WorkloadCompoundName *string                                 `json:"workloadCompoundName,omitempty"`
	LogLevel             *string                                 `json:"logLevel,omitempty"`
	LogFormat            *string                                 `json:"logFormat,omitempty"`
}

// FlightdeckSpecApplyConfiguration constructs a declarative configuration of the FlightdeckSpec type for use with
// apply.
func FlightdeckSpec() *FlightdeckSpecApplyConfiguration {
	return &FlightdeckSpecApplyConfiguration{}
}

// WithSiteName sets the SiteName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SiteName field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithSiteName(value string) *FlightdeckSpecApplyConfiguration {
	b.SiteName = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithImage(value string) *FlightdeckSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *FlightdeckSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithPort(value int32) *FlightdeckSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithReplicas(value int) *FlightdeckSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithFeatureEnabler sets the FeatureEnabler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FeatureEnabler field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithFeatureEnabler(value *FeatureEnablerConfigApplyConfiguration) *FlightdeckSpecApplyConfiguration {
	b.FeatureEnabler = value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithDomain(value string) *FlightdeckSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithIngressClass sets the IngressClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClass field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithIngressClass(value string) *FlightdeckSpecApplyConfiguration {
	b.IngressClass = &value
	return b
}

// WithIngressAnnotations puts the entries into the IngressAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the IngressAnnotations field,
// overwriting an existing map entries in IngressAnnotations field with the same key.
func (b *FlightdeckSpecApplyConfiguration) WithIngressAnnotations(entries map[string]string) *FlightdeckSpecApplyConfiguration {
	if b.IngressAnnotations == nil && len(entries) > 0 {
		b.IngressAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.IngressAnnotations[k] = v
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *FlightdeckSpecApplyConfiguration) WithImagePullSecrets(values ...string) *FlightdeckSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithAwsAccountId sets the AwsAccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AwsAccountId field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithAwsAccountId(value string) *FlightdeckSpecApplyConfiguration {
	b.AwsAccountId = &value
	return b
}

// WithClusterDate sets the ClusterDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDate field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithClusterDate(value string) *FlightdeckSpecApplyConfiguration {
	b.ClusterDate = &value
	return b
}

// WithWorkloadCompoundName sets the WorkloadCompoundName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadCompoundName field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithWorkloadCompoundName(value string) *FlightdeckSpecApplyConfiguration {
	b.WorkloadCompoundName = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithLogLevel(value string) *FlightdeckSpecApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithLogFormat sets the LogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogFormat field is set to the value of the last call.
func (b *FlightdeckSpecApplyConfiguration) WithLogFormat(value string) *FlightdeckSpecApplyConfiguration {
	b.LogFormat = &value
	return b
}
