// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// GatewayReferenceApplyConfiguration represents a declarative configuration of the GatewayReference type for use
// with apply.
type GatewayReferenceApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// GatewayReferenceApplyConfiguration constructs a declarative configuration of the GatewayReference type for use with
// apply.
func GatewayReference() *GatewayReferenceApplyConfiguration {
	return &GatewayReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GatewayReferenceApplyConfiguration) WithName(value string) *GatewayReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *GatewayReferenceApplyConfiguration) WithNamespace(value string) *GatewayReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
