// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	product "github.com/posit-dev/team-operator/api/product"
	v1 "k8s.io/api/core/v1"
)

// InternalPackageManagerSpecApplyConfiguration represents a declarative configuration of the InternalPackageManagerSpec type for use
// with apply.
type InternalPackageManagerSpecApplyConfiguration struct {
	License         *product.LicenseSpec                `json:"license,omitempty"`
	Volume          *product.VolumeSpec                 `json:"volume,omitempty"`
	NodeSelector    map[string]string                   `json:"nodeSelector,omitempty"`
	AddEnv          map[string]string                   `json:"addEnv,omitempty"`
	Image           *string                             `json:"image,omitempty"`
	ImagePullPolicy *v1.PullPolicy                      `json:"imagePullPolicy,omitempty"`
	S3Bucket        *string                             `json:"s3Bucket,omitempty"`
	Replicas        *int                                `json:"replicas,omitempty"`
	DomainPrefix    *string                             `json:"domainPrefix,omitempty"`
	GitSSHKeys      []SSHKeyConfigApplyConfiguration    `json:"gitSSHKeys,omitempty"`
	AzureFiles      *AzureFilesConfigApplyConfiguration `json:"azureFiles,omitempty"`
}

// InternalPackageManagerSpecApplyConfiguration constructs a declarative configuration of the InternalPackageManagerSpec type for use with
// apply.
func InternalPackageManagerSpec() *InternalPackageManagerSpecApplyConfiguration {
	return &InternalPackageManagerSpecApplyConfiguration{}
}

// WithLicense sets the License field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the License field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithLicense(value product.LicenseSpec) *InternalPackageManagerSpecApplyConfiguration {
	b.License = &value
	return b
}

// WithVolume sets the Volume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Volume field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithVolume(value product.VolumeSpec) *InternalPackageManagerSpecApplyConfiguration {
	b.Volume = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *InternalPackageManagerSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *InternalPackageManagerSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithAddEnv puts the entries into the AddEnv field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AddEnv field,
// overwriting an existing map entries in AddEnv field with the same key.
func (b *InternalPackageManagerSpecApplyConfiguration) WithAddEnv(entries map[string]string) *InternalPackageManagerSpecApplyConfiguration {
	if b.AddEnv == nil && len(entries) > 0 {
		b.AddEnv = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AddEnv[k] = v
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithImage(value string) *InternalPackageManagerSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *InternalPackageManagerSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithS3Bucket sets the S3Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Bucket field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithS3Bucket(value string) *InternalPackageManagerSpecApplyConfiguration {
	b.S3Bucket = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithReplicas(value int) *InternalPackageManagerSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithDomainPrefix sets the DomainPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainPrefix field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithDomainPrefix(value string) *InternalPackageManagerSpecApplyConfiguration {
	b.DomainPrefix = &value
	return b
}

// WithGitSSHKeys adds the given value to the GitSSHKeys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GitSSHKeys field.
func (b *InternalPackageManagerSpecApplyConfiguration) WithGitSSHKeys(values ...*SSHKeyConfigApplyConfiguration) *InternalPackageManagerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGitSSHKeys")
		}
		b.GitSSHKeys = append(b.GitSSHKeys, *values[i])
	}
	return b
}

// WithAzureFiles sets the AzureFiles field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AzureFiles field is set to the value of the last call.
func (b *InternalPackageManagerSpecApplyConfiguration) WithAzureFiles(value *AzureFilesConfigApplyConfiguration) *InternalPackageManagerSpecApplyConfiguration {
	b.AzureFiles = value
	return b
}
