// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// InternalKeycloakSpecApplyConfiguration represents a declarative configuration of the InternalKeycloakSpec type for use
// with apply.
type InternalKeycloakSpecApplyConfiguration struct {
	Enabled         *bool             `json:"enabled,omitempty"`
	Image           *string           `json:"image,omitempty"`
	ImagePullPolicy *v1.PullPolicy    `json:"imagePullPolicy,omitempty"`
	NodeSelector    map[string]string `json:"nodeSelector,omitempty"`
}

// InternalKeycloakSpecApplyConfiguration constructs a declarative configuration of the InternalKeycloakSpec type for use with
// apply.
func InternalKeycloakSpec() *InternalKeycloakSpecApplyConfiguration {
	return &InternalKeycloakSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *InternalKeycloakSpecApplyConfiguration) WithEnabled(value bool) *InternalKeycloakSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *InternalKeycloakSpecApplyConfiguration) WithImage(value string) *InternalKeycloakSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *InternalKeycloakSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *InternalKeycloakSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *InternalKeycloakSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *InternalKeycloakSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}
