// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// InternalChronicleSpecApplyConfiguration represents a declarative configuration of the InternalChronicleSpec type for use
// with apply.
type InternalChronicleSpecApplyConfiguration struct {
	NodeSelector    map[string]string `json:"nodeSelector,omitempty"`
	Image           *string           `json:"image,omitempty"`
	AddEnv          map[string]string `json:"addEnv,omitempty"`
	ImagePullPolicy *v1.PullPolicy    `json:"imagePullPolicy,omitempty"`
	S3Bucket        *string           `json:"s3Bucket,omitempty"`
	AgentImage      *string           `json:"agentImage,omitempty"`
}

// InternalChronicleSpecApplyConfiguration constructs a declarative configuration of the InternalChronicleSpec type for use with
// apply.
func InternalChronicleSpec() *InternalChronicleSpecApplyConfiguration {
	return &InternalChronicleSpecApplyConfiguration{}
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *InternalChronicleSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *InternalChronicleSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *InternalChronicleSpecApplyConfiguration) WithImage(value string) *InternalChronicleSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithAddEnv puts the entries into the AddEnv field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AddEnv field,
// overwriting an existing map entries in AddEnv field with the same key.
func (b *InternalChronicleSpecApplyConfiguration) WithAddEnv(entries map[string]string) *InternalChronicleSpecApplyConfiguration {
	if b.AddEnv == nil && len(entries) > 0 {
		b.AddEnv = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AddEnv[k] = v
	}
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *InternalChronicleSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *InternalChronicleSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithS3Bucket sets the S3Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Bucket field is set to the value of the last call.
func (b *InternalChronicleSpecApplyConfiguration) WithS3Bucket(value string) *InternalChronicleSpecApplyConfiguration {
	b.S3Bucket = &value
	return b
}

// WithAgentImage sets the AgentImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentImage field is set to the value of the last call.
func (b *InternalChronicleSpecApplyConfiguration) WithAgentImage(value string) *InternalChronicleSpecApplyConfiguration {
	b.AgentImage = &value
	return b
}
