// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerConfigApplyConfiguration represents a declarative configuration of the PackageManagerConfig type for use
// with apply.
type PackageManagerConfigApplyConfiguration struct {
	Server    *PackageManagerServerConfigApplyConfiguration    `json:"Server,omitempty"`
	Http      *PackageManagerHttpConfigApplyConfiguration      `json:"Http,omitempty"`
	Git       *PackageManagerGitConfigApplyConfiguration       `json:"Git,omitempty"`
	Database  *PackageManagerDatabaseConfigApplyConfiguration  `json:"Database,omitempty"`
	Postgres  *PackageManagerPostgresConfigApplyConfiguration  `json:"Postgres,omitempty"`
	Storage   *PackageManagerStorageConfigApplyConfiguration   `json:"Storage,omitempty"`
	S3Storage *PackageManagerS3StorageConfigApplyConfiguration `json:"S3Storage,omitempty"`
	Metrics   *PackageManagerMetricsConfigApplyConfiguration   `json:"Metrics,omitempty"`
	Repos     *PackageManagerReposConfigApplyConfiguration     `json:"Repos,omitempty"`
	Cran      *PackageManagerCRANConfigApplyConfiguration      `json:"CRAN,omitempty"`
	Debug     *PackageManagerDebugConfigApplyConfiguration     `json:"Debug,omitempty"`
}

// PackageManagerConfigApplyConfiguration constructs a declarative configuration of the PackageManagerConfig type for use with
// apply.
func PackageManagerConfig() *PackageManagerConfigApplyConfiguration {
	return &PackageManagerConfigApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithServer(value *PackageManagerServerConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Server = value
	return b
}

// WithHttp sets the Http field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Http field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithHttp(value *PackageManagerHttpConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Http = value
	return b
}

// WithGit sets the Git field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Git field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithGit(value *PackageManagerGitConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Git = value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithDatabase(value *PackageManagerDatabaseConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Database = value
	return b
}

// WithPostgres sets the Postgres field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Postgres field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithPostgres(value *PackageManagerPostgresConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Postgres = value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithStorage(value *PackageManagerStorageConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Storage = value
	return b
}

// WithS3Storage sets the S3Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Storage field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithS3Storage(value *PackageManagerS3StorageConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.S3Storage = value
	return b
}

// WithMetrics sets the Metrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metrics field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithMetrics(value *PackageManagerMetricsConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Metrics = value
	return b
}

// WithRepos sets the Repos field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repos field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithRepos(value *PackageManagerReposConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Repos = value
	return b
}

// WithCran sets the Cran field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cran field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithCran(value *PackageManagerCRANConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Cran = value
	return b
}

// WithDebug sets the Debug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Debug field is set to the value of the last call.
func (b *PackageManagerConfigApplyConfiguration) WithDebug(value *PackageManagerDebugConfigApplyConfiguration) *PackageManagerConfigApplyConfiguration {
	b.Debug = value
	return b
}
