// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerGitConfigApplyConfiguration represents a declarative configuration of the PackageManagerGitConfig type for use
// with apply.
type PackageManagerGitConfigApplyConfiguration struct {
	AllowUnsandboxedGitBuilds *bool `json:"AllowUnsandboxedGitBuilds,omitempty"`
}

// PackageManagerGitConfigApplyConfiguration constructs a declarative configuration of the PackageManagerGitConfig type for use with
// apply.
func PackageManagerGitConfig() *PackageManagerGitConfigApplyConfiguration {
	return &PackageManagerGitConfigApplyConfiguration{}
}

// WithAllowUnsandboxedGitBuilds sets the AllowUnsandboxedGitBuilds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowUnsandboxedGitBuilds field is set to the value of the last call.
func (b *PackageManagerGitConfigApplyConfiguration) WithAllowUnsandboxedGitBuilds(value bool) *PackageManagerGitConfigApplyConfiguration {
	b.AllowUnsandboxedGitBuilds = &value
	return b
}
