// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerS3StorageConfigApplyConfiguration represents a declarative configuration of the PackageManagerS3StorageConfig type for use
// with apply.
type PackageManagerS3StorageConfigApplyConfiguration struct {
	Bucket *string `json:"Bucket,omitempty"`
	Prefix *string `json:"Prefix,omitempty"`
	Region *string `json:"Region,omitempty"`
}

// PackageManagerS3StorageConfigApplyConfiguration constructs a declarative configuration of the PackageManagerS3StorageConfig type for use with
// apply.
func PackageManagerS3StorageConfig() *PackageManagerS3StorageConfigApplyConfiguration {
	return &PackageManagerS3StorageConfigApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *PackageManagerS3StorageConfigApplyConfiguration) WithBucket(value string) *PackageManagerS3StorageConfigApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *PackageManagerS3StorageConfigApplyConfiguration) WithPrefix(value string) *PackageManagerS3StorageConfigApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *PackageManagerS3StorageConfigApplyConfiguration) WithRegion(value string) *PackageManagerS3StorageConfigApplyConfiguration {
	b.Region = &value
	return b
}
