// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerReposConfigApplyConfiguration represents a declarative configuration of the PackageManagerReposConfig type for use
// with apply.
type PackageManagerReposConfigApplyConfiguration struct {
	PyPI         *string `json:"PyPI,omitempty"`
	CRAN         *string `json:"CRAN,omitempty"`
	Bioconductor *string `json:"Bioconductor,omitempty"`
}

// PackageManagerReposConfigApplyConfiguration constructs a declarative configuration of the PackageManagerReposConfig type for use with
// apply.
func PackageManagerReposConfig() *PackageManagerReposConfigApplyConfiguration {
	return &PackageManagerReposConfigApplyConfiguration{}
}

// WithPyPI sets the PyPI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PyPI field is set to the value of the last call.
func (b *PackageManagerReposConfigApplyConfiguration) WithPyPI(value string) *PackageManagerReposConfigApplyConfiguration {
	b.PyPI = &value
	return b
}

// WithCRAN sets the CRAN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CRAN field is set to the value of the last call.
func (b *PackageManagerReposConfigApplyConfiguration) WithCRAN(value string) *PackageManagerReposConfigApplyConfiguration {
	b.CRAN = &value
	return b
}

// WithBioconductor sets the Bioconductor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bioconductor field is set to the value of the last call.
func (b *PackageManagerReposConfigApplyConfiguration) WithBioconductor(value string) *PackageManagerReposConfigApplyConfiguration {
	b.Bioconductor = &value
	return b
}
