// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// PackageManagerServerConfigApplyConfiguration represents a declarative configuration of the PackageManagerServerConfig type for use
// with apply.
type PackageManagerServerConfigApplyConfiguration struct {
	Address         *string                                    `json:"Address,omitempty"`
	RVersion        []string                                   `json:"RVersion,omitempty"`
	LauncherDir     *string                                    `json:"LauncherDir,omitempty"`
	AccessLog       *string                                    `json:"AccessLog,omitempty"`
	AccessLogFormat *corev1beta1.PackageManagerAccessLogFormat `json:"AccessLogFormat,omitempty"`
	DataDir         *string                                    `json:"DataDir,omitempty"`
}

// PackageManagerServerConfigApplyConfiguration constructs a declarative configuration of the PackageManagerServerConfig type for use with
// apply.
func PackageManagerServerConfig() *PackageManagerServerConfigApplyConfiguration {
	return &PackageManagerServerConfigApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *PackageManagerServerConfigApplyConfiguration) WithAddress(value string) *PackageManagerServerConfigApplyConfiguration {
	b.Address = &value
	return b
}

// WithRVersion adds the given value to the RVersion field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RVersion field.
func (b *PackageManagerServerConfigApplyConfiguration) WithRVersion(values ...string) *PackageManagerServerConfigApplyConfiguration {
	for i := range values {
		b.RVersion = append(b.RVersion, values[i])
	}
	return b
}

// WithLauncherDir sets the LauncherDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LauncherDir field is set to the value of the last call.
func (b *PackageManagerServerConfigApplyConfiguration) WithLauncherDir(value string) *PackageManagerServerConfigApplyConfiguration {
	b.LauncherDir = &value
	return b
}

// WithAccessLog sets the AccessLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessLog field is set to the value of the last call.
func (b *PackageManagerServerConfigApplyConfiguration) WithAccessLog(value string) *PackageManagerServerConfigApplyConfiguration {
	b.AccessLog = &value
	return b
}

// WithAccessLogFormat sets the AccessLogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessLogFormat field is set to the value of the last call.
func (b *PackageManagerServerConfigApplyConfiguration) WithAccessLogFormat(value corev1beta1.PackageManagerAccessLogFormat) *PackageManagerServerConfigApplyConfiguration {
	b.AccessLogFormat = &value
	return b
}

// WithDataDir sets the DataDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDir field is set to the value of the last call.
func (b *PackageManagerServerConfigApplyConfiguration) WithDataDir(value string) *PackageManagerServerConfigApplyConfiguration {
	b.DataDir = &value
	return b
}
