// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerAuthenticationConfigApplyConfiguration represents a declarative configuration of the PackageManagerAuthenticationConfig type for use
// with apply.
type PackageManagerAuthenticationConfigApplyConfiguration struct {
	APITokenAuth          *bool   `json:"APITokenAuth,omitempty"`
	DeviceAuthType        *string `json:"DeviceAuthType,omitempty"`
	NewReposAuthByDefault *bool   `json:"NewReposAuthByDefault,omitempty"`
	Lifetime              *string `json:"Lifetime,omitempty"`
	Inactivity            *string `json:"Inactivity,omitempty"`
	CookieSweepDuration   *string `json:"CookieSweepDuration,omitempty"`
}

// PackageManagerAuthenticationConfigApplyConfiguration constructs a declarative configuration of the PackageManagerAuthenticationConfig type for use with
// apply.
func PackageManagerAuthenticationConfig() *PackageManagerAuthenticationConfigApplyConfiguration {
	return &PackageManagerAuthenticationConfigApplyConfiguration{}
}

// WithAPITokenAuth sets the APITokenAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APITokenAuth field is set to the value of the last call.
func (b *PackageManagerAuthenticationConfigApplyConfiguration) WithAPITokenAuth(value bool) *PackageManagerAuthenticationConfigApplyConfiguration {
	b.APITokenAuth = &value
	return b
}

// WithDeviceAuthType sets the DeviceAuthType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceAuthType field is set to the value of the last call.
func (b *PackageManagerAuthenticationConfigApplyConfiguration) WithDeviceAuthType(value string) *PackageManagerAuthenticationConfigApplyConfiguration {
	b.DeviceAuthType = &value
	return b
}

// WithNewReposAuthByDefault sets the NewReposAuthByDefault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NewReposAuthByDefault field is set to the value of the last call.
func (b *PackageManagerAuthenticationConfigApplyConfiguration) WithNewReposAuthByDefault(value bool) *PackageManagerAuthenticationConfigApplyConfiguration {
	b.NewReposAuthByDefault = &value
	return b
}

// WithLifetime sets the Lifetime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifetime field is set to the value of the last call.
func (b *PackageManagerAuthenticationConfigApplyConfiguration) WithLifetime(value string) *PackageManagerAuthenticationConfigApplyConfiguration {
	b.Lifetime = &value
	return b
}

// WithInactivity sets the Inactivity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inactivity field is set to the value of the last call.
func (b *PackageManagerAuthenticationConfigApplyConfiguration) WithInactivity(value string) *PackageManagerAuthenticationConfigApplyConfiguration {
	b.Inactivity = &value
	return b
}

// WithCookieSweepDuration sets the CookieSweepDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CookieSweepDuration field is set to the value of the last call.
func (b *PackageManagerAuthenticationConfigApplyConfiguration) WithCookieSweepDuration(value string) *PackageManagerAuthenticationConfigApplyConfiguration {
	b.CookieSweepDuration = &value
	return b
}
