// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerCRANConfigApplyConfiguration represents a declarative configuration of the PackageManagerCRANConfig type for use
// with apply.
type PackageManagerCRANConfigApplyConfiguration struct {
	RSF *bool `json:"RSF,omitempty"`
}

// PackageManagerCRANConfigApplyConfiguration constructs a declarative configuration of the PackageManagerCRANConfig type for use with
// apply.
func PackageManagerCRANConfig() *PackageManagerCRANConfigApplyConfiguration {
	return &PackageManagerCRANConfigApplyConfiguration{}
}

// WithRSF sets the RSF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RSF field is set to the value of the last call.
func (b *PackageManagerCRANConfigApplyConfiguration) WithRSF(value bool) *PackageManagerCRANConfigApplyConfiguration {
	b.RSF = &value
	return b
}
