// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerOIDCConfigApplyConfiguration represents a declarative configuration of the PackageManagerOIDCConfig type for use
// with apply.
type PackageManagerOIDCConfigApplyConfiguration struct {
	ClientId     *string `json:"ClientId,omitempty"`
	ClientSecret *string `json:"ClientSecret,omitempty"`
	Issuer       *string `json:"Issuer,omitempty"`
	RequireLogin *bool   `json:"RequireLogin,omitempty"`
	Scope        *string `json:"Scope,omitempty"`
	GroupsClaim  *string `json:"GroupsClaim,omitempty"`
	RoleClaim    *string `json:"RoleClaim,omitempty"`
}

// PackageManagerOIDCConfigApplyConfiguration constructs a declarative configuration of the PackageManagerOIDCConfig type for use with
// apply.
func PackageManagerOIDCConfig() *PackageManagerOIDCConfigApplyConfiguration {
	return &PackageManagerOIDCConfigApplyConfiguration{}
}

// WithClientId sets the ClientId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientId field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithClientId(value string) *PackageManagerOIDCConfigApplyConfiguration {
	b.ClientId = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithClientSecret(value string) *PackageManagerOIDCConfigApplyConfiguration {
	b.ClientSecret = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithIssuer(value string) *PackageManagerOIDCConfigApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithRequireLogin sets the RequireLogin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireLogin field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithRequireLogin(value bool) *PackageManagerOIDCConfigApplyConfiguration {
	b.RequireLogin = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithScope(value string) *PackageManagerOIDCConfigApplyConfiguration {
	b.Scope = &value
	return b
}

// WithGroupsClaim sets the GroupsClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupsClaim field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithGroupsClaim(value string) *PackageManagerOIDCConfigApplyConfiguration {
	b.GroupsClaim = &value
	return b
}

// WithRoleClaim sets the RoleClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleClaim field is set to the value of the last call.
func (b *PackageManagerOIDCConfigApplyConfiguration) WithRoleClaim(value string) *PackageManagerOIDCConfigApplyConfiguration {
	b.RoleClaim = &value
	return b
}
