// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerPostgresConfigApplyConfiguration represents a declarative configuration of the PackageManagerPostgresConfig type for use
// with apply.
type PackageManagerPostgresConfigApplyConfiguration struct {
	URL          *string `json:"URL,omitempty"`
	UsageDataURL *string `json:"UsageDataURL,omitempty"`
}

// PackageManagerPostgresConfigApplyConfiguration constructs a declarative configuration of the PackageManagerPostgresConfig type for use with
// apply.
func PackageManagerPostgresConfig() *PackageManagerPostgresConfigApplyConfiguration {
	return &PackageManagerPostgresConfigApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *PackageManagerPostgresConfigApplyConfiguration) WithURL(value string) *PackageManagerPostgresConfigApplyConfiguration {
	b.URL = &value
	return b
}

// WithUsageDataURL sets the UsageDataURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsageDataURL field is set to the value of the last call.
func (b *PackageManagerPostgresConfigApplyConfiguration) WithUsageDataURL(value string) *PackageManagerPostgresConfigApplyConfiguration {
	b.UsageDataURL = &value
	return b
}
