// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerDatabaseConfigApplyConfiguration represents a declarative configuration of the PackageManagerDatabaseConfig type for use
// with apply.
type PackageManagerDatabaseConfigApplyConfiguration struct {
	Provider *string `json:"Provider,omitempty"`
}

// PackageManagerDatabaseConfigApplyConfiguration constructs a declarative configuration of the PackageManagerDatabaseConfig type for use with
// apply.
func PackageManagerDatabaseConfig() *PackageManagerDatabaseConfigApplyConfiguration {
	return &PackageManagerDatabaseConfigApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *PackageManagerDatabaseConfigApplyConfiguration) WithProvider(value string) *PackageManagerDatabaseConfigApplyConfiguration {
	b.Provider = &value
	return b
}
