// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PackageManagerIdentityFederationConfigApplyConfiguration represents a declarative configuration of the PackageManagerIdentityFederationConfig type for use
// with apply.
type PackageManagerIdentityFederationConfigApplyConfiguration struct {
	Issuer          *string `json:"Issuer,omitempty"`
	Audience        *string `json:"Audience,omitempty"`
	Subject         *string `json:"Subject,omitempty"`
	AuthorizedParty *string `json:"AuthorizedParty,omitempty"`
	Scope           *string `json:"Scope,omitempty"`
	TokenLifetime   *string `json:"TokenLifetime,omitempty"`
}

// PackageManagerIdentityFederationConfigApplyConfiguration constructs a declarative configuration of the PackageManagerIdentityFederationConfig type for use with
// apply.
func PackageManagerIdentityFederationConfig() *PackageManagerIdentityFederationConfigApplyConfiguration {
	return &PackageManagerIdentityFederationConfigApplyConfiguration{}
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *PackageManagerIdentityFederationConfigApplyConfiguration) WithIssuer(value string) *PackageManagerIdentityFederationConfigApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *PackageManagerIdentityFederationConfigApplyConfiguration) WithAudience(value string) *PackageManagerIdentityFederationConfigApplyConfiguration {
	b.Audience = &value
	return b
}

// WithSubject sets the Subject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subject field is set to the value of the last call.
func (b *PackageManagerIdentityFederationConfigApplyConfiguration) WithSubject(value string) *PackageManagerIdentityFederationConfigApplyConfiguration {
	b.Subject = &value
	return b
}

// WithAuthorizedParty sets the AuthorizedParty field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorizedParty field is set to the value of the last call.
func (b *PackageManagerIdentityFederationConfigApplyConfiguration) WithAuthorizedParty(value string) *PackageManagerIdentityFederationConfigApplyConfiguration {
	b.AuthorizedParty = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *PackageManagerIdentityFederationConfigApplyConfiguration) WithScope(value string) *PackageManagerIdentityFederationConfigApplyConfiguration {
	b.Scope = &value
	return b
}

// WithTokenLifetime sets the TokenLifetime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenLifetime field is set to the value of the last call.
func (b *PackageManagerIdentityFederationConfigApplyConfiguration) WithTokenLifetime(value string) *PackageManagerIdentityFederationConfigApplyConfiguration {
	b.TokenLifetime = &value
	return b
}
