// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	product "github.com/posit-dev/team-operator/api/product"
	v1 "k8s.io/api/core/v1"
)

// PackageManagerSpecApplyConfiguration represents a declarative configuration of the PackageManagerSpec type for use
// with apply.
type PackageManagerSpecApplyConfiguration struct {
	License                      *product.LicenseSpec                      `json:"license,omitempty"`
	Config                       *PackageManagerConfigApplyConfiguration   `json:"config,omitempty"`
	Volume                       *product.VolumeSpec                       `json:"volume,omitempty"`
	SecretType                   *product.SiteSecretType                   `json:"secretType,omitempty"`
	Url                          *string                                   `json:"url,omitempty"`
	DatabaseConfig               *PostgresDatabaseConfigApplyConfiguration `json:"databaseConfig,omitempty"`
	IngressClass                 *string                                   `json:"ingressClass,omitempty"`
	IngressAnnotations           map[string]string                         `json:"ingressAnnotations,omitempty"`
	ImagePullSecrets             []string                                  `json:"imagePullSecrets,omitempty"`
	NodeSelector                 map[string]string                         `json:"nodeSelector,omitempty"`
	AddEnv                       map[string]string                         `json:"addEnv,omitempty"`
	Image                        *string                                   `json:"image,omitempty"`
	ImagePullPolicy              *v1.PullPolicy                            `json:"imagePullPolicy,omitempty"`
	Sleep                        *bool                                     `json:"sleep,omitempty"`
	AwsAccountId                 *string                                   `json:"awsAccountId,omitempty"`
	WorkloadCompoundName         *string                                   `json:"workloadCompoundName,omitempty"`
	ClusterDate                  *string                                   `json:"clusterDate,omitempty"`
	ChronicleAgentImage          *string                                   `json:"chronicleImage,omitempty"`
	Secret                       *SecretConfigApplyConfiguration           `json:"secret,omitempty"`
	WorkloadSecret               *SecretConfigApplyConfiguration           `json:"workloadSecret,omitempty"`
	MainDatabaseCredentialSecret *SecretConfigApplyConfiguration           `json:"mainDatabaseCredentialSecret,omitempty"`
	Replicas                     *int                                      `json:"replicas,omitempty"`
	GitSSHKeys                   []SSHKeyConfigApplyConfiguration          `json:"gitSSHKeys,omitempty"`
	AzureFiles                   *AzureFilesConfigApplyConfiguration       `json:"azureFiles,omitempty"`
}

// PackageManagerSpecApplyConfiguration constructs a declarative configuration of the PackageManagerSpec type for use with
// apply.
func PackageManagerSpec() *PackageManagerSpecApplyConfiguration {
	return &PackageManagerSpecApplyConfiguration{}
}

// WithLicense sets the License field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the License field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithLicense(value product.LicenseSpec) *PackageManagerSpecApplyConfiguration {
	b.License = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithConfig(value *PackageManagerConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithVolume sets the Volume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Volume field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithVolume(value product.VolumeSpec) *PackageManagerSpecApplyConfiguration {
	b.Volume = &value
	return b
}

// WithSecretType sets the SecretType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretType field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithSecretType(value product.SiteSecretType) *PackageManagerSpecApplyConfiguration {
	b.SecretType = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithUrl(value string) *PackageManagerSpecApplyConfiguration {
	b.Url = &value
	return b
}

// WithDatabaseConfig sets the DatabaseConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DatabaseConfig field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithDatabaseConfig(value *PostgresDatabaseConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	b.DatabaseConfig = value
	return b
}

// WithIngressClass sets the IngressClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClass field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithIngressClass(value string) *PackageManagerSpecApplyConfiguration {
	b.IngressClass = &value
	return b
}

// WithIngressAnnotations puts the entries into the IngressAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the IngressAnnotations field,
// overwriting an existing map entries in IngressAnnotations field with the same key.
func (b *PackageManagerSpecApplyConfiguration) WithIngressAnnotations(entries map[string]string) *PackageManagerSpecApplyConfiguration {
	if b.IngressAnnotations == nil && len(entries) > 0 {
		b.IngressAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.IngressAnnotations[k] = v
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *PackageManagerSpecApplyConfiguration) WithImagePullSecrets(values ...string) *PackageManagerSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *PackageManagerSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *PackageManagerSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithAddEnv puts the entries into the AddEnv field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AddEnv field,
// overwriting an existing map entries in AddEnv field with the same key.
func (b *PackageManagerSpecApplyConfiguration) WithAddEnv(entries map[string]string) *PackageManagerSpecApplyConfiguration {
	if b.AddEnv == nil && len(entries) > 0 {
		b.AddEnv = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AddEnv[k] = v
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithImage(value string) *PackageManagerSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *PackageManagerSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithSleep sets the Sleep field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sleep field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithSleep(value bool) *PackageManagerSpecApplyConfiguration {
	b.Sleep = &value
	return b
}

// WithAwsAccountId sets the AwsAccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AwsAccountId field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithAwsAccountId(value string) *PackageManagerSpecApplyConfiguration {
	b.AwsAccountId = &value
	return b
}

// WithWorkloadCompoundName sets the WorkloadCompoundName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadCompoundName field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithWorkloadCompoundName(value string) *PackageManagerSpecApplyConfiguration {
	b.WorkloadCompoundName = &value
	return b
}

// WithClusterDate sets the ClusterDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDate field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithClusterDate(value string) *PackageManagerSpecApplyConfiguration {
	b.ClusterDate = &value
	return b
}

// WithChronicleAgentImage sets the ChronicleAgentImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChronicleAgentImage field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithChronicleAgentImage(value string) *PackageManagerSpecApplyConfiguration {
	b.ChronicleAgentImage = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithSecret(value *SecretConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	b.Secret = value
	return b
}

// WithWorkloadSecret sets the WorkloadSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadSecret field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithWorkloadSecret(value *SecretConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	b.WorkloadSecret = value
	return b
}

// WithMainDatabaseCredentialSecret sets the MainDatabaseCredentialSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainDatabaseCredentialSecret field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithMainDatabaseCredentialSecret(value *SecretConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	b.MainDatabaseCredentialSecret = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithReplicas(value int) *PackageManagerSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithGitSSHKeys adds the given value to the GitSSHKeys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GitSSHKeys field.
func (b *PackageManagerSpecApplyConfiguration) WithGitSSHKeys(values ...*SSHKeyConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGitSSHKeys")
		}
		b.GitSSHKeys = append(b.GitSSHKeys, *values[i])
	}
	return b
}

// WithAzureFiles sets the AzureFiles field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AzureFiles field is set to the value of the last call.
func (b *PackageManagerSpecApplyConfiguration) WithAzureFiles(value *AzureFilesConfigApplyConfiguration) *PackageManagerSpecApplyConfiguration {
	b.AzureFiles = value
	return b
}
