// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// PackageManagerStatusApplyConfiguration represents a declarative configuration of the PackageManagerStatus type for use
// with apply.
type PackageManagerStatusApplyConfiguration struct {
	KeySecretRef *v1.SecretReference `json:"keySecretRef,omitempty"`
	Ready        *bool               `json:"ready,omitempty"`
}

// PackageManagerStatusApplyConfiguration constructs a declarative configuration of the PackageManagerStatus type for use with
// apply.
func PackageManagerStatus() *PackageManagerStatusApplyConfiguration {
	return &PackageManagerStatusApplyConfiguration{}
}

// WithKeySecretRef sets the KeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeySecretRef field is set to the value of the last call.
func (b *PackageManagerStatusApplyConfiguration) WithKeySecretRef(value v1.SecretReference) *PackageManagerStatusApplyConfiguration {
	b.KeySecretRef = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *PackageManagerStatusApplyConfiguration) WithReady(value bool) *PackageManagerStatusApplyConfiguration {
	b.Ready = &value
	return b
}
