// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// PositronConfigApplyConfiguration represents a declarative configuration of the PositronConfig type for use
// with apply.
type PositronConfigApplyConfiguration struct {
	Enabled                      *int                `json:"enabled,omitempty"`
	Exe                          *string             `json:"exe,omitempty"`
	Args                         *string             `json:"args,omitempty"`
	DefaultSessionContainerImage *string             `json:"defaultSessionContainerImage,omitempty"`
	SessionContainerImages       []string            `json:"sessionContainerImages,omitempty"`
	PositronSessionPath          *string             `json:"positronSessionPath,omitempty"`
	SessionNoProfile             *int                `json:"sessionNoProfile,omitempty"`
	UserDataDir                  *string             `json:"userDataDir,omitempty"`
	AllowFileDownloads           *int                `json:"allowFileDownloads,omitempty"`
	AllowFileUploads             *int                `json:"allowFileUploads,omitempty"`
	SessionTimeoutKillHours      *int                `json:"sessionTimeoutKillHours,omitempty"`
	Extensions                   []string            `json:"extensions,omitempty"`
	UserSettings                 map[string]*v1.JSON `json:"userSettings,omitempty"`
}

// PositronConfigApplyConfiguration constructs a declarative configuration of the PositronConfig type for use with
// apply.
func PositronConfig() *PositronConfigApplyConfiguration {
	return &PositronConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithEnabled(value int) *PositronConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithExe sets the Exe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exe field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithExe(value string) *PositronConfigApplyConfiguration {
	b.Exe = &value
	return b
}

// WithArgs sets the Args field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Args field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithArgs(value string) *PositronConfigApplyConfiguration {
	b.Args = &value
	return b
}

// WithDefaultSessionContainerImage sets the DefaultSessionContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultSessionContainerImage field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithDefaultSessionContainerImage(value string) *PositronConfigApplyConfiguration {
	b.DefaultSessionContainerImage = &value
	return b
}

// WithSessionContainerImages adds the given value to the SessionContainerImages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SessionContainerImages field.
func (b *PositronConfigApplyConfiguration) WithSessionContainerImages(values ...string) *PositronConfigApplyConfiguration {
	for i := range values {
		b.SessionContainerImages = append(b.SessionContainerImages, values[i])
	}
	return b
}

// WithPositronSessionPath sets the PositronSessionPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PositronSessionPath field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithPositronSessionPath(value string) *PositronConfigApplyConfiguration {
	b.PositronSessionPath = &value
	return b
}

// WithSessionNoProfile sets the SessionNoProfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionNoProfile field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithSessionNoProfile(value int) *PositronConfigApplyConfiguration {
	b.SessionNoProfile = &value
	return b
}

// WithUserDataDir sets the UserDataDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserDataDir field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithUserDataDir(value string) *PositronConfigApplyConfiguration {
	b.UserDataDir = &value
	return b
}

// WithAllowFileDownloads sets the AllowFileDownloads field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowFileDownloads field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithAllowFileDownloads(value int) *PositronConfigApplyConfiguration {
	b.AllowFileDownloads = &value
	return b
}

// WithAllowFileUploads sets the AllowFileUploads field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowFileUploads field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithAllowFileUploads(value int) *PositronConfigApplyConfiguration {
	b.AllowFileUploads = &value
	return b
}

// WithSessionTimeoutKillHours sets the SessionTimeoutKillHours field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionTimeoutKillHours field is set to the value of the last call.
func (b *PositronConfigApplyConfiguration) WithSessionTimeoutKillHours(value int) *PositronConfigApplyConfiguration {
	b.SessionTimeoutKillHours = &value
	return b
}

// WithExtensions adds the given value to the Extensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Extensions field.
func (b *PositronConfigApplyConfiguration) WithExtensions(values ...string) *PositronConfigApplyConfiguration {
	for i := range values {
		b.Extensions = append(b.Extensions, values[i])
	}
	return b
}

// WithUserSettings puts the entries into the UserSettings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the UserSettings field,
// overwriting an existing map entries in UserSettings field with the same key.
func (b *PositronConfigApplyConfiguration) WithUserSettings(entries map[string]*v1.JSON) *PositronConfigApplyConfiguration {
	if b.UserSettings == nil && len(entries) > 0 {
		b.UserSettings = make(map[string]*v1.JSON, len(entries))
	}
	for k, v := range entries {
		b.UserSettings[k] = v
	}
	return b
}
