// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PostgresDatabaseSpecTeardownApplyConfiguration represents a declarative configuration of the PostgresDatabaseSpecTeardown type for use
// with apply.
type PostgresDatabaseSpecTeardownApplyConfiguration struct {
	Drop *bool `json:"drop,omitempty"`
}

// PostgresDatabaseSpecTeardownApplyConfiguration constructs a declarative configuration of the PostgresDatabaseSpecTeardown type for use with
// apply.
func PostgresDatabaseSpecTeardown() *PostgresDatabaseSpecTeardownApplyConfiguration {
	return &PostgresDatabaseSpecTeardownApplyConfiguration{}
}

// WithDrop sets the Drop field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Drop field is set to the value of the last call.
func (b *PostgresDatabaseSpecTeardownApplyConfiguration) WithDrop(value bool) *PostgresDatabaseSpecTeardownApplyConfiguration {
	b.Drop = &value
	return b
}
