// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PostgresDatabaseSpecApplyConfiguration represents a declarative configuration of the PostgresDatabaseSpec type for use
// with apply.
type PostgresDatabaseSpecApplyConfiguration struct {
	URL                          *string                                         `json:"url,omitempty"`
	SecretVault                  *string                                         `json:"secretVault,omitempty"`
	SecretPasswordKey            *string                                         `json:"secretPasswordKey,omitempty"`
	Secret                       *SecretConfigApplyConfiguration                 `json:"secret,omitempty"`
	WorkloadSecret               *SecretConfigApplyConfiguration                 `json:"workloadSecret,omitempty"`
	MainDatabaseCredentialSecret *SecretConfigApplyConfiguration                 `json:"mainDbCredentialSecret,omitempty"`
	Extensions                   []string                                        `json:"extensions,omitempty"`
	Schemas                      []string                                        `json:"schemas,omitempty"`
	Teardown                     *PostgresDatabaseSpecTeardownApplyConfiguration `json:"teardown,omitempty"`
}

// PostgresDatabaseSpecApplyConfiguration constructs a declarative configuration of the PostgresDatabaseSpec type for use with
// apply.
func PostgresDatabaseSpec() *PostgresDatabaseSpecApplyConfiguration {
	return &PostgresDatabaseSpecApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithURL(value string) *PostgresDatabaseSpecApplyConfiguration {
	b.URL = &value
	return b
}

// WithSecretVault sets the SecretVault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretVault field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithSecretVault(value string) *PostgresDatabaseSpecApplyConfiguration {
	b.SecretVault = &value
	return b
}

// WithSecretPasswordKey sets the SecretPasswordKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretPasswordKey field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithSecretPasswordKey(value string) *PostgresDatabaseSpecApplyConfiguration {
	b.SecretPasswordKey = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithSecret(value *SecretConfigApplyConfiguration) *PostgresDatabaseSpecApplyConfiguration {
	b.Secret = value
	return b
}

// WithWorkloadSecret sets the WorkloadSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadSecret field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithWorkloadSecret(value *SecretConfigApplyConfiguration) *PostgresDatabaseSpecApplyConfiguration {
	b.WorkloadSecret = value
	return b
}

// WithMainDatabaseCredentialSecret sets the MainDatabaseCredentialSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainDatabaseCredentialSecret field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithMainDatabaseCredentialSecret(value *SecretConfigApplyConfiguration) *PostgresDatabaseSpecApplyConfiguration {
	b.MainDatabaseCredentialSecret = value
	return b
}

// WithExtensions adds the given value to the Extensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Extensions field.
func (b *PostgresDatabaseSpecApplyConfiguration) WithExtensions(values ...string) *PostgresDatabaseSpecApplyConfiguration {
	for i := range values {
		b.Extensions = append(b.Extensions, values[i])
	}
	return b
}

// WithSchemas adds the given value to the Schemas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Schemas field.
func (b *PostgresDatabaseSpecApplyConfiguration) WithSchemas(values ...string) *PostgresDatabaseSpecApplyConfiguration {
	for i := range values {
		b.Schemas = append(b.Schemas, values[i])
	}
	return b
}

// WithTeardown sets the Teardown field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Teardown field is set to the value of the last call.
func (b *PostgresDatabaseSpecApplyConfiguration) WithTeardown(value *PostgresDatabaseSpecTeardownApplyConfiguration) *PostgresDatabaseSpecApplyConfiguration {
	b.Teardown = value
	return b
}
