// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PostgresDatabaseStatusApplyConfiguration represents a declarative configuration of the PostgresDatabaseStatus type for use
// with apply.
type PostgresDatabaseStatusApplyConfiguration struct {
	CommonProductStatusApplyConfiguration `json:",inline"`
}

// PostgresDatabaseStatusApplyConfiguration constructs a declarative configuration of the PostgresDatabaseStatus type for use with
// apply.
func PostgresDatabaseStatus() *PostgresDatabaseStatusApplyConfiguration {
	return &PostgresDatabaseStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PostgresDatabaseStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *PostgresDatabaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.CommonProductStatusApplyConfiguration.Conditions = append(b.CommonProductStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PostgresDatabaseStatusApplyConfiguration) WithObservedGeneration(value int64) *PostgresDatabaseStatusApplyConfiguration {
	b.CommonProductStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *PostgresDatabaseStatusApplyConfiguration) WithVersion(value string) *PostgresDatabaseStatusApplyConfiguration {
	b.CommonProductStatusApplyConfiguration.Version = &value
	return b
}
