// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// RPackageRepositoryConfigApplyConfiguration represents a declarative configuration of the RPackageRepositoryConfig type for use
// with apply.
type RPackageRepositoryConfigApplyConfiguration struct {
	Url *string `json:"Url,omitempty"`
}

// RPackageRepositoryConfigApplyConfiguration constructs a declarative configuration of the RPackageRepositoryConfig type for use with
// apply.
func RPackageRepositoryConfig() *RPackageRepositoryConfigApplyConfiguration {
	return &RPackageRepositoryConfigApplyConfiguration{}
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *RPackageRepositoryConfigApplyConfiguration) WithUrl(value string) *RPackageRepositoryConfigApplyConfiguration {
	b.Url = &value
	return b
}
