// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	product "github.com/posit-dev/team-operator/api/product"
)

// SecretConfigApplyConfiguration represents a declarative configuration of the SecretConfig type for use
// with apply.
type SecretConfigApplyConfiguration struct {
	VaultName *string                 `json:"vaultName,omitempty"`
	Type      *product.SiteSecretType `json:"type,omitempty"`
}

// SecretConfigApplyConfiguration constructs a declarative configuration of the SecretConfig type for use with
// apply.
func SecretConfig() *SecretConfigApplyConfiguration {
	return &SecretConfigApplyConfiguration{}
}

// WithVaultName sets the VaultName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VaultName field is set to the value of the last call.
func (b *SecretConfigApplyConfiguration) WithVaultName(value string) *SecretConfigApplyConfiguration {
	b.VaultName = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SecretConfigApplyConfiguration) WithType(value product.SiteSecretType) *SecretConfigApplyConfiguration {
	b.Type = &value
	return b
}
