// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ServiceAccountConfigApplyConfiguration represents a declarative configuration of the ServiceAccountConfig type for use
// with apply.
type ServiceAccountConfigApplyConfiguration struct {
	NameSuffix  *string           `json:"nameSuffix,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// ServiceAccountConfigApplyConfiguration constructs a declarative configuration of the ServiceAccountConfig type for use with
// apply.
func ServiceAccountConfig() *ServiceAccountConfigApplyConfiguration {
	return &ServiceAccountConfigApplyConfiguration{}
}

// WithNameSuffix sets the NameSuffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NameSuffix field is set to the value of the last call.
func (b *ServiceAccountConfigApplyConfiguration) WithNameSuffix(value string) *ServiceAccountConfigApplyConfiguration {
	b.NameSuffix = &value
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ServiceAccountConfigApplyConfiguration) WithAnnotations(entries map[string]string) *ServiceAccountConfigApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
