// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SessionLabelsConfigApplyConfiguration represents a declarative configuration of the SessionLabelsConfig type for use
// with apply.
type SessionLabelsConfigApplyConfiguration struct {
	SourceField    *string `json:"sourceField,omitempty"`
	SourceKey      *string `json:"sourceKey,omitempty"`
	SearchRegex    *string `json:"searchRegex,omitempty"`
	LabelKeyPrefix *string `json:"labelKeyPrefix,omitempty"`
	TrimPrefix     *string `json:"trimPrefix,omitempty"`
}

// SessionLabelsConfigApplyConfiguration constructs a declarative configuration of the SessionLabelsConfig type for use with
// apply.
func SessionLabelsConfig() *SessionLabelsConfigApplyConfiguration {
	return &SessionLabelsConfigApplyConfiguration{}
}

// WithSourceField sets the SourceField field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceField field is set to the value of the last call.
func (b *SessionLabelsConfigApplyConfiguration) WithSourceField(value string) *SessionLabelsConfigApplyConfiguration {
	b.SourceField = &value
	return b
}

// WithSourceKey sets the SourceKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceKey field is set to the value of the last call.
func (b *SessionLabelsConfigApplyConfiguration) WithSourceKey(value string) *SessionLabelsConfigApplyConfiguration {
	b.SourceKey = &value
	return b
}

// WithSearchRegex sets the SearchRegex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchRegex field is set to the value of the last call.
func (b *SessionLabelsConfigApplyConfiguration) WithSearchRegex(value string) *SessionLabelsConfigApplyConfiguration {
	b.SearchRegex = &value
	return b
}

// WithLabelKeyPrefix sets the LabelKeyPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelKeyPrefix field is set to the value of the last call.
func (b *SessionLabelsConfigApplyConfiguration) WithLabelKeyPrefix(value string) *SessionLabelsConfigApplyConfiguration {
	b.LabelKeyPrefix = &value
	return b
}

// WithTrimPrefix sets the TrimPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrimPrefix field is set to the value of the last call.
func (b *SessionLabelsConfigApplyConfiguration) WithTrimPrefix(value string) *SessionLabelsConfigApplyConfiguration {
	b.TrimPrefix = &value
	return b
}
