// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	product "github.com/posit-dev/team-operator/api/product"
)

// SiteSpecApplyConfiguration represents a declarative configuration of the SiteSpec type for use
// with apply.
type SiteSpecApplyConfiguration struct {
	AwsAccountId                 *string                                       `json:"awsAccountId,omitempty"`
	ClusterDate                  *string                                       `json:"clusterDate,omitempty"`
	WorkloadCompoundName         *string                                       `json:"workloadCompoundName,omitempty"`
	Domain                       *string                                       `json:"domain,omitempty"`
	SecretType                   *product.SiteSecretType                       `json:"secretType,omitempty"`
	Flightdeck                   *InternalFlightdeckSpecApplyConfiguration     `json:"flightdeck,omitempty"`
	PackageManager               *InternalPackageManagerSpecApplyConfiguration `json:"packageManager,omitempty"`
	Connect                      *InternalConnectSpecApplyConfiguration        `json:"connect,omitempty"`
	Workbench                    *InternalWorkbenchSpecApplyConfiguration      `json:"workbench,omitempty"`
	Chronicle                    *InternalChronicleSpecApplyConfiguration      `json:"chronicle,omitempty"`
	Keycloak                     *InternalKeycloakSpecApplyConfiguration       `json:"keycloak,omitempty"`
	IngressClass                 *string                                       `json:"ingressClass,omitempty"`
	IngressAnnotations           map[string]string                             `json:"ingressAnnotations,omitempty"`
	ImagePullSecrets             []string                                      `json:"imagePullSecrets,omitempty"`
	VolumeSource                 *VolumeSourceApplyConfiguration               `json:"volumeSource,omitempty"`
	SharedDirectory              *string                                       `json:"sharedDirectory,omitempty"`
	VolumeSubdirJobOff           *bool                                         `json:"volumeSubdirJobOff,omitempty"`
	ExtraSiteServiceAccounts     []ServiceAccountConfigApplyConfiguration      `json:"extraSiteServiceAccounts,omitempty"`
	Secret                       *SecretConfigApplyConfiguration               `json:"secret,omitempty"`
	WorkloadSecret               *SecretConfigApplyConfiguration               `json:"workloadSecret,omitempty"`
	DisablePrePullImages         *bool                                         `json:"disablePrePullImages,omitempty"`
	MainDatabaseCredentialSecret *SecretConfigApplyConfiguration               `json:"mainDatabaseCredentialSecret,omitempty"`
	DropDatabaseOnTeardown       *bool                                         `json:"dropDatabaseOnTearDown,omitempty"`
	Debug                        *bool                                         `json:"debug,omitempty"`
	LogFormat                    *product.LogFormat                            `json:"logFormat,omitempty"`
	NetworkTrust                 *corev1beta1.NetworkTrust                     `json:"networkTrust,omitempty"`
	PackageManagerUrl            *string                                       `json:"packageManagerUrl,omitempty"`
	EFSEnabled                   *bool                                         `json:"efsEnabled,omitempty"`
	VPCCIDR                      *string                                       `json:"vpcCIDR,omitempty"`
	EnableFQDNHealthChecks       *bool                                         `json:"enableFqdnHealthChecks,omitempty"`
}

// SiteSpecApplyConfiguration constructs a declarative configuration of the SiteSpec type for use with
// apply.
func SiteSpec() *SiteSpecApplyConfiguration {
	return &SiteSpecApplyConfiguration{}
}

// WithAwsAccountId sets the AwsAccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AwsAccountId field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithAwsAccountId(value string) *SiteSpecApplyConfiguration {
	b.AwsAccountId = &value
	return b
}

// WithClusterDate sets the ClusterDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDate field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithClusterDate(value string) *SiteSpecApplyConfiguration {
	b.ClusterDate = &value
	return b
}

// WithWorkloadCompoundName sets the WorkloadCompoundName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadCompoundName field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithWorkloadCompoundName(value string) *SiteSpecApplyConfiguration {
	b.WorkloadCompoundName = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithDomain(value string) *SiteSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithSecretType sets the SecretType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretType field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithSecretType(value product.SiteSecretType) *SiteSpecApplyConfiguration {
	b.SecretType = &value
	return b
}

// WithFlightdeck sets the Flightdeck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Flightdeck field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithFlightdeck(value *InternalFlightdeckSpecApplyConfiguration) *SiteSpecApplyConfiguration {
	b.Flightdeck = value
	return b
}

// WithPackageManager sets the PackageManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PackageManager field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithPackageManager(value *InternalPackageManagerSpecApplyConfiguration) *SiteSpecApplyConfiguration {
	b.PackageManager = value
	return b
}

// WithConnect sets the Connect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Connect field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithConnect(value *InternalConnectSpecApplyConfiguration) *SiteSpecApplyConfiguration {
	b.Connect = value
	return b
}

// WithWorkbench sets the Workbench field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workbench field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithWorkbench(value *InternalWorkbenchSpecApplyConfiguration) *SiteSpecApplyConfiguration {
	b.Workbench = value
	return b
}

// WithChronicle sets the Chronicle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Chronicle field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithChronicle(value *InternalChronicleSpecApplyConfiguration) *SiteSpecApplyConfiguration {
	b.Chronicle = value
	return b
}

// WithKeycloak sets the Keycloak field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Keycloak field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithKeycloak(value *InternalKeycloakSpecApplyConfiguration) *SiteSpecApplyConfiguration {
	b.Keycloak = value
	return b
}

// WithIngressClass sets the IngressClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClass field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithIngressClass(value string) *SiteSpecApplyConfiguration {
	b.IngressClass = &value
	return b
}

// WithIngressAnnotations puts the entries into the IngressAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the IngressAnnotations field,
// overwriting an existing map entries in IngressAnnotations field with the same key.
func (b *SiteSpecApplyConfiguration) WithIngressAnnotations(entries map[string]string) *SiteSpecApplyConfiguration {
	if b.IngressAnnotations == nil && len(entries) > 0 {
		b.IngressAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.IngressAnnotations[k] = v
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *SiteSpecApplyConfiguration) WithImagePullSecrets(values ...string) *SiteSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithVolumeSource sets the VolumeSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSource field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithVolumeSource(value *VolumeSourceApplyConfiguration) *SiteSpecApplyConfiguration {
	b.VolumeSource = value
	return b
}

// WithSharedDirectory sets the SharedDirectory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SharedDirectory field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithSharedDirectory(value string) *SiteSpecApplyConfiguration {
	b.SharedDirectory = &value
	return b
}

// WithVolumeSubdirJobOff sets the VolumeSubdirJobOff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSubdirJobOff field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithVolumeSubdirJobOff(value bool) *SiteSpecApplyConfiguration {
	b.VolumeSubdirJobOff = &value
	return b
}

// WithExtraSiteServiceAccounts adds the given value to the ExtraSiteServiceAccounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraSiteServiceAccounts field.
func (b *SiteSpecApplyConfiguration) WithExtraSiteServiceAccounts(values ...*ServiceAccountConfigApplyConfiguration) *SiteSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExtraSiteServiceAccounts")
		}
		b.ExtraSiteServiceAccounts = append(b.ExtraSiteServiceAccounts, *values[i])
	}
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithSecret(value *SecretConfigApplyConfiguration) *SiteSpecApplyConfiguration {
	b.Secret = value
	return b
}

// WithWorkloadSecret sets the WorkloadSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadSecret field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithWorkloadSecret(value *SecretConfigApplyConfiguration) *SiteSpecApplyConfiguration {
	b.WorkloadSecret = value
	return b
}

// WithDisablePrePullImages sets the DisablePrePullImages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisablePrePullImages field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithDisablePrePullImages(value bool) *SiteSpecApplyConfiguration {
	b.DisablePrePullImages = &value
	return b
}

// WithMainDatabaseCredentialSecret sets the MainDatabaseCredentialSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainDatabaseCredentialSecret field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithMainDatabaseCredentialSecret(value *SecretConfigApplyConfiguration) *SiteSpecApplyConfiguration {
	b.MainDatabaseCredentialSecret = value
	return b
}

// WithDropDatabaseOnTeardown sets the DropDatabaseOnTeardown field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DropDatabaseOnTeardown field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithDropDatabaseOnTeardown(value bool) *SiteSpecApplyConfiguration {
	b.DropDatabaseOnTeardown = &value
	return b
}

// WithDebug sets the Debug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Debug field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithDebug(value bool) *SiteSpecApplyConfiguration {
	b.Debug = &value
	return b
}

// WithLogFormat sets the LogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogFormat field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithLogFormat(value product.LogFormat) *SiteSpecApplyConfiguration {
	b.LogFormat = &value
	return b
}

// WithNetworkTrust sets the NetworkTrust field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkTrust field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithNetworkTrust(value corev1beta1.NetworkTrust) *SiteSpecApplyConfiguration {
	b.NetworkTrust = &value
	return b
}

// WithPackageManagerUrl sets the PackageManagerUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PackageManagerUrl field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithPackageManagerUrl(value string) *SiteSpecApplyConfiguration {
	b.PackageManagerUrl = &value
	return b
}

// WithEFSEnabled sets the EFSEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EFSEnabled field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithEFSEnabled(value bool) *SiteSpecApplyConfiguration {
	b.EFSEnabled = &value
	return b
}

// WithVPCCIDR sets the VPCCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPCCIDR field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithVPCCIDR(value string) *SiteSpecApplyConfiguration {
	b.VPCCIDR = &value
	return b
}

// WithEnableFQDNHealthChecks sets the EnableFQDNHealthChecks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableFQDNHealthChecks field is set to the value of the last call.
func (b *SiteSpecApplyConfiguration) WithEnableFQDNHealthChecks(value bool) *SiteSpecApplyConfiguration {
	b.EnableFQDNHealthChecks = &value
	return b
}
