// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SiteStatusApplyConfiguration represents a declarative configuration of the SiteStatus type for use
// with apply.
type SiteStatusApplyConfiguration struct {
	CommonProductStatusApplyConfiguration `json:",inline"`
	ConnectReady                          *bool `json:"connectReady,omitempty"`
	WorkbenchReady                        *bool `json:"workbenchReady,omitempty"`
	PackageManagerReady                   *bool `json:"packageManagerReady,omitempty"`
	ChronicleReady                        *bool `json:"chronicleReady,omitempty"`
	FlightdeckReady                       *bool `json:"flightdeckReady,omitempty"`
}

// SiteStatusApplyConfiguration constructs a declarative configuration of the SiteStatus type for use with
// apply.
func SiteStatus() *SiteStatusApplyConfiguration {
	return &SiteStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SiteStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SiteStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.CommonProductStatusApplyConfiguration.Conditions = append(b.CommonProductStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithObservedGeneration(value int64) *SiteStatusApplyConfiguration {
	b.CommonProductStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithVersion(value string) *SiteStatusApplyConfiguration {
	b.CommonProductStatusApplyConfiguration.Version = &value
	return b
}

// WithConnectReady sets the ConnectReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectReady field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithConnectReady(value bool) *SiteStatusApplyConfiguration {
	b.ConnectReady = &value
	return b
}

// WithWorkbenchReady sets the WorkbenchReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkbenchReady field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithWorkbenchReady(value bool) *SiteStatusApplyConfiguration {
	b.WorkbenchReady = &value
	return b
}

// WithPackageManagerReady sets the PackageManagerReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PackageManagerReady field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithPackageManagerReady(value bool) *SiteStatusApplyConfiguration {
	b.PackageManagerReady = &value
	return b
}

// WithChronicleReady sets the ChronicleReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChronicleReady field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithChronicleReady(value bool) *SiteStatusApplyConfiguration {
	b.ChronicleReady = &value
	return b
}

// WithFlightdeckReady sets the FlightdeckReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlightdeckReady field is set to the value of the last call.
func (b *SiteStatusApplyConfiguration) WithFlightdeckReady(value bool) *SiteStatusApplyConfiguration {
	b.FlightdeckReady = &value
	return b
}
