// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SnowflakeConfigApplyConfiguration represents a declarative configuration of the SnowflakeConfig type for use
// with apply.
type SnowflakeConfigApplyConfiguration struct {
	AccountId *string `json:"accountId,omitempty"`
	ClientId  *string `json:"clientId,omitempty"`
}

// SnowflakeConfigApplyConfiguration constructs a declarative configuration of the SnowflakeConfig type for use with
// apply.
func SnowflakeConfig() *SnowflakeConfigApplyConfiguration {
	return &SnowflakeConfigApplyConfiguration{}
}

// WithAccountId sets the AccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountId field is set to the value of the last call.
func (b *SnowflakeConfigApplyConfiguration) WithAccountId(value string) *SnowflakeConfigApplyConfiguration {
	b.AccountId = &value
	return b
}

// WithClientId sets the ClientId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientId field is set to the value of the last call.
func (b *SnowflakeConfigApplyConfiguration) WithClientId(value string) *SnowflakeConfigApplyConfiguration {
	b.ClientId = &value
	return b
}
