// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SSHKeyConfigApplyConfiguration represents a declarative configuration of the SSHKeyConfig type for use
// with apply.
type SSHKeyConfigApplyConfiguration struct {
	Name                *string                            `json:"name,omitempty"`
	Host                *string                            `json:"host,omitempty"`
	SecretRef           *SecretReferenceApplyConfiguration `json:"secretRef,omitempty"`
	PassphraseSecretRef *SecretReferenceApplyConfiguration `json:"passphraseSecretRef,omitempty"`
}

// SSHKeyConfigApplyConfiguration constructs a declarative configuration of the SSHKeyConfig type for use with
// apply.
func SSHKeyConfig() *SSHKeyConfigApplyConfiguration {
	return &SSHKeyConfigApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SSHKeyConfigApplyConfiguration) WithName(value string) *SSHKeyConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *SSHKeyConfigApplyConfiguration) WithHost(value string) *SSHKeyConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *SSHKeyConfigApplyConfiguration) WithSecretRef(value *SecretReferenceApplyConfiguration) *SSHKeyConfigApplyConfiguration {
	b.SecretRef = value
	return b
}

// WithPassphraseSecretRef sets the PassphraseSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PassphraseSecretRef field is set to the value of the last call.
func (b *SSHKeyConfigApplyConfiguration) WithPassphraseSecretRef(value *SecretReferenceApplyConfiguration) *SSHKeyConfigApplyConfiguration {
	b.PassphraseSecretRef = value
	return b
}
