// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// SupervisordIniConfigApplyConfiguration represents a declarative configuration of the SupervisordIniConfig type for use
// with apply.
type SupervisordIniConfigApplyConfiguration struct {
	Programs map[string]map[string]*corev1beta1.SupervisordProgramConfig `json:"programs.conf,omitempty"`
}

// SupervisordIniConfigApplyConfiguration constructs a declarative configuration of the SupervisordIniConfig type for use with
// apply.
func SupervisordIniConfig() *SupervisordIniConfigApplyConfiguration {
	return &SupervisordIniConfigApplyConfiguration{}
}

// WithPrograms puts the entries into the Programs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Programs field,
// overwriting an existing map entries in Programs field with the same key.
func (b *SupervisordIniConfigApplyConfiguration) WithPrograms(entries map[string]map[string]*corev1beta1.SupervisordProgramConfig) *SupervisordIniConfigApplyConfiguration {
	if b.Programs == nil && len(entries) > 0 {
		b.Programs = make(map[string]map[string]*corev1beta1.SupervisordProgramConfig, len(entries))
	}
	for k, v := range entries {
		b.Programs[k] = v
	}
	return b
}
