// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SupervisordProgramConfigApplyConfiguration represents a declarative configuration of the SupervisordProgramConfig type for use
// with apply.
type SupervisordProgramConfigApplyConfiguration struct {
	User                  *string `json:"user,omitempty"`
	Command               *string `json:"command,omitempty"`
	AutoRestart           *bool   `json:"autorestart,omitempty"`
	NumProcs              *int    `json:"numprocs,omitempty"`
	StdOutLogFile         *string `json:"stdout_logfile,omitempty"`
	StdOutLogFileMaxBytes *int    `json:"stdout_logfile_maxbytes,omitempty"`
	StdErrLogFile         *string `json:"stderr_logfile,omitempty"`
	StdErrLogFileMaxBytes *int    `json:"stderr_logfile_maxbytes,omitempty"`
	Environment           *string `json:"environment,omitempty"`
}

// SupervisordProgramConfigApplyConfiguration constructs a declarative configuration of the SupervisordProgramConfig type for use with
// apply.
func SupervisordProgramConfig() *SupervisordProgramConfigApplyConfiguration {
	return &SupervisordProgramConfigApplyConfiguration{}
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithUser(value string) *SupervisordProgramConfigApplyConfiguration {
	b.User = &value
	return b
}

// WithCommand sets the Command field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Command field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithCommand(value string) *SupervisordProgramConfigApplyConfiguration {
	b.Command = &value
	return b
}

// WithAutoRestart sets the AutoRestart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoRestart field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithAutoRestart(value bool) *SupervisordProgramConfigApplyConfiguration {
	b.AutoRestart = &value
	return b
}

// WithNumProcs sets the NumProcs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumProcs field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithNumProcs(value int) *SupervisordProgramConfigApplyConfiguration {
	b.NumProcs = &value
	return b
}

// WithStdOutLogFile sets the StdOutLogFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StdOutLogFile field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithStdOutLogFile(value string) *SupervisordProgramConfigApplyConfiguration {
	b.StdOutLogFile = &value
	return b
}

// WithStdOutLogFileMaxBytes sets the StdOutLogFileMaxBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StdOutLogFileMaxBytes field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithStdOutLogFileMaxBytes(value int) *SupervisordProgramConfigApplyConfiguration {
	b.StdOutLogFileMaxBytes = &value
	return b
}

// WithStdErrLogFile sets the StdErrLogFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StdErrLogFile field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithStdErrLogFile(value string) *SupervisordProgramConfigApplyConfiguration {
	b.StdErrLogFile = &value
	return b
}

// WithStdErrLogFileMaxBytes sets the StdErrLogFileMaxBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StdErrLogFileMaxBytes field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithStdErrLogFileMaxBytes(value int) *SupervisordProgramConfigApplyConfiguration {
	b.StdErrLogFileMaxBytes = &value
	return b
}

// WithEnvironment sets the Environment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Environment field is set to the value of the last call.
func (b *SupervisordProgramConfigApplyConfiguration) WithEnvironment(value string) *SupervisordProgramConfigApplyConfiguration {
	b.Environment = &value
	return b
}
