// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
)

// VolumeSourceApplyConfiguration represents a declarative configuration of the VolumeSource type for use
// with apply.
type VolumeSourceApplyConfiguration struct {
	Type     *corev1beta1.VolumeSourceType `json:"type,omitempty"`
	VolumeId *string                       `json:"volumeId,omitempty"`
	DnsName  *string                       `json:"dnsName,omitempty"`
}

// VolumeSourceApplyConfiguration constructs a declarative configuration of the VolumeSource type for use with
// apply.
func VolumeSource() *VolumeSourceApplyConfiguration {
	return &VolumeSourceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *VolumeSourceApplyConfiguration) WithType(value corev1beta1.VolumeSourceType) *VolumeSourceApplyConfiguration {
	b.Type = &value
	return b
}

// WithVolumeId sets the VolumeId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeId field is set to the value of the last call.
func (b *VolumeSourceApplyConfiguration) WithVolumeId(value string) *VolumeSourceApplyConfiguration {
	b.VolumeId = &value
	return b
}

// WithDnsName sets the DnsName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DnsName field is set to the value of the last call.
func (b *VolumeSourceApplyConfiguration) WithDnsName(value string) *VolumeSourceApplyConfiguration {
	b.DnsName = &value
	return b
}
