// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// VSCodeConfigApplyConfiguration represents a declarative configuration of the VSCodeConfig type for use
// with apply.
type VSCodeConfigApplyConfiguration struct {
	Enabled                 *int    `json:"enabled,omitempty"`
	Exe                     *string `json:"exe,omitempty"`
	Args                    *string `json:"args,omitempty"`
	SessionTimeoutKillHours *int    `json:"sessionTimeoutKillHours,omitempty"`
}

// VSCodeConfigApplyConfiguration constructs a declarative configuration of the VSCodeConfig type for use with
// apply.
func VSCodeConfig() *VSCodeConfigApplyConfiguration {
	return &VSCodeConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *VSCodeConfigApplyConfiguration) WithEnabled(value int) *VSCodeConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithExe sets the Exe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exe field is set to the value of the last call.
func (b *VSCodeConfigApplyConfiguration) WithExe(value string) *VSCodeConfigApplyConfiguration {
	b.Exe = &value
	return b
}

// WithArgs sets the Args field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Args field is set to the value of the last call.
func (b *VSCodeConfigApplyConfiguration) WithArgs(value string) *VSCodeConfigApplyConfiguration {
	b.Args = &value
	return b
}

// WithSessionTimeoutKillHours sets the SessionTimeoutKillHours field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionTimeoutKillHours field is set to the value of the last call.
func (b *VSCodeConfigApplyConfiguration) WithSessionTimeoutKillHours(value int) *VSCodeConfigApplyConfiguration {
	b.SessionTimeoutKillHours = &value
	return b
}
