// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	applyconfigurationcorev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	scheme "github.com/posit-dev/team-operator/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ChroniclesGetter has a method to return a ChronicleInterface.
// A group's client should implement this interface.
type ChroniclesGetter interface {
	Chronicles(namespace string) ChronicleInterface
}

// ChronicleInterface has methods to work with Chronicle resources.
type ChronicleInterface interface {
	Create(ctx context.Context, chronicle *corev1beta1.Chronicle, opts v1.CreateOptions) (*corev1beta1.Chronicle, error)
	Update(ctx context.Context, chronicle *corev1beta1.Chronicle, opts v1.UpdateOptions) (*corev1beta1.Chronicle, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, chronicle *corev1beta1.Chronicle, opts v1.UpdateOptions) (*corev1beta1.Chronicle, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.Chronicle, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.ChronicleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.Chronicle, err error)
	Apply(ctx context.Context, chronicle *applyconfigurationcorev1beta1.ChronicleApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.Chronicle, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, chronicle *applyconfigurationcorev1beta1.ChronicleApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.Chronicle, err error)
	ChronicleExpansion
}

// chronicles implements ChronicleInterface
type chronicles struct {
	*gentype.ClientWithListAndApply[*corev1beta1.Chronicle, *corev1beta1.ChronicleList, *applyconfigurationcorev1beta1.ChronicleApplyConfiguration]
}

// newChronicles returns a Chronicles
func newChronicles(c *CoreV1beta1Client, namespace string) *chronicles {
	return &chronicles{
		gentype.NewClientWithListAndApply[*corev1beta1.Chronicle, *corev1beta1.ChronicleList, *applyconfigurationcorev1beta1.ChronicleApplyConfiguration](
			"chronicles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1beta1.Chronicle { return &corev1beta1.Chronicle{} },
			func() *corev1beta1.ChronicleList { return &corev1beta1.ChronicleList{} },
		),
	}
}
