// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	applyconfigurationcorev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	scheme "github.com/posit-dev/team-operator/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ConnectsGetter has a method to return a ConnectInterface.
// A group's client should implement this interface.
type ConnectsGetter interface {
	Connects(namespace string) ConnectInterface
}

// ConnectInterface has methods to work with Connect resources.
type ConnectInterface interface {
	Create(ctx context.Context, connect *corev1beta1.Connect, opts v1.CreateOptions) (*corev1beta1.Connect, error)
	Update(ctx context.Context, connect *corev1beta1.Connect, opts v1.UpdateOptions) (*corev1beta1.Connect, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, connect *corev1beta1.Connect, opts v1.UpdateOptions) (*corev1beta1.Connect, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.Connect, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.ConnectList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.Connect, err error)
	Apply(ctx context.Context, connect *applyconfigurationcorev1beta1.ConnectApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.Connect, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, connect *applyconfigurationcorev1beta1.ConnectApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.Connect, err error)
	ConnectExpansion
}

// connects implements ConnectInterface
type connects struct {
	*gentype.ClientWithListAndApply[*corev1beta1.Connect, *corev1beta1.ConnectList, *applyconfigurationcorev1beta1.ConnectApplyConfiguration]
}

// newConnects returns a Connects
func newConnects(c *CoreV1beta1Client, namespace string) *connects {
	return &connects{
		gentype.NewClientWithListAndApply[*corev1beta1.Connect, *corev1beta1.ConnectList, *applyconfigurationcorev1beta1.ConnectApplyConfiguration](
			"connects",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1beta1.Connect { return &corev1beta1.Connect{} },
			func() *corev1beta1.ConnectList { return &corev1beta1.ConnectList{} },
		),
	}
}
