// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	applyconfigurationcorev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	scheme "github.com/posit-dev/team-operator/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FlightdecksGetter has a method to return a FlightdeckInterface.
// A group's client should implement this interface.
type FlightdecksGetter interface {
	Flightdecks(namespace string) FlightdeckInterface
}

// FlightdeckInterface has methods to work with Flightdeck resources.
type FlightdeckInterface interface {
	Create(ctx context.Context, flightdeck *corev1beta1.Flightdeck, opts v1.CreateOptions) (*corev1beta1.Flightdeck, error)
	Update(ctx context.Context, flightdeck *corev1beta1.Flightdeck, opts v1.UpdateOptions) (*corev1beta1.Flightdeck, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, flightdeck *corev1beta1.Flightdeck, opts v1.UpdateOptions) (*corev1beta1.Flightdeck, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.Flightdeck, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.FlightdeckList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.Flightdeck, err error)
	Apply(ctx context.Context, flightdeck *applyconfigurationcorev1beta1.FlightdeckApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.Flightdeck, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, flightdeck *applyconfigurationcorev1beta1.FlightdeckApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.Flightdeck, err error)
	FlightdeckExpansion
}

// flightdecks implements FlightdeckInterface
type flightdecks struct {
	*gentype.ClientWithListAndApply[*corev1beta1.Flightdeck, *corev1beta1.FlightdeckList, *applyconfigurationcorev1beta1.FlightdeckApplyConfiguration]
}

// newFlightdecks returns a Flightdecks
func newFlightdecks(c *CoreV1beta1Client, namespace string) *flightdecks {
	return &flightdecks{
		gentype.NewClientWithListAndApply[*corev1beta1.Flightdeck, *corev1beta1.FlightdeckList, *applyconfigurationcorev1beta1.FlightdeckApplyConfiguration](
			"flightdecks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1beta1.Flightdeck { return &corev1beta1.Flightdeck{} },
			func() *corev1beta1.FlightdeckList { return &corev1beta1.FlightdeckList{} },
		),
	}
}
