// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type ChronicleExpansion interface{}

type ConnectExpansion interface{}

type FlightdeckExpansion interface{}

type PackageManagerExpansion interface{}

type PostgresDatabaseExpansion interface{}

type SiteExpansion interface{}

type WorkbenchExpansion interface{}
