// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	applyconfigurationcorev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	scheme "github.com/posit-dev/team-operator/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PackageManagersGetter has a method to return a PackageManagerInterface.
// A group's client should implement this interface.
type PackageManagersGetter interface {
	PackageManagers(namespace string) PackageManagerInterface
}

// PackageManagerInterface has methods to work with PackageManager resources.
type PackageManagerInterface interface {
	Create(ctx context.Context, packageManager *corev1beta1.PackageManager, opts v1.CreateOptions) (*corev1beta1.PackageManager, error)
	Update(ctx context.Context, packageManager *corev1beta1.PackageManager, opts v1.UpdateOptions) (*corev1beta1.PackageManager, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, packageManager *corev1beta1.PackageManager, opts v1.UpdateOptions) (*corev1beta1.PackageManager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.PackageManager, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.PackageManagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.PackageManager, err error)
	Apply(ctx context.Context, packageManager *applyconfigurationcorev1beta1.PackageManagerApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.PackageManager, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, packageManager *applyconfigurationcorev1beta1.PackageManagerApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.PackageManager, err error)
	PackageManagerExpansion
}

// packageManagers implements PackageManagerInterface
type packageManagers struct {
	*gentype.ClientWithListAndApply[*corev1beta1.PackageManager, *corev1beta1.PackageManagerList, *applyconfigurationcorev1beta1.PackageManagerApplyConfiguration]
}

// newPackageManagers returns a PackageManagers
func newPackageManagers(c *CoreV1beta1Client, namespace string) *packageManagers {
	return &packageManagers{
		gentype.NewClientWithListAndApply[*corev1beta1.PackageManager, *corev1beta1.PackageManagerList, *applyconfigurationcorev1beta1.PackageManagerApplyConfiguration](
			"packagemanagers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1beta1.PackageManager { return &corev1beta1.PackageManager{} },
			func() *corev1beta1.PackageManagerList { return &corev1beta1.PackageManagerList{} },
		),
	}
}
