// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	corev1beta1 "github.com/posit-dev/team-operator/api/core/v1beta1"
	applyconfigurationcorev1beta1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/core/v1beta1"
	scheme "github.com/posit-dev/team-operator/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PostgresDatabasesGetter has a method to return a PostgresDatabaseInterface.
// A group's client should implement this interface.
type PostgresDatabasesGetter interface {
	PostgresDatabases(namespace string) PostgresDatabaseInterface
}

// PostgresDatabaseInterface has methods to work with PostgresDatabase resources.
type PostgresDatabaseInterface interface {
	Create(ctx context.Context, postgresDatabase *corev1beta1.PostgresDatabase, opts v1.CreateOptions) (*corev1beta1.PostgresDatabase, error)
	Update(ctx context.Context, postgresDatabase *corev1beta1.PostgresDatabase, opts v1.UpdateOptions) (*corev1beta1.PostgresDatabase, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, postgresDatabase *corev1beta1.PostgresDatabase, opts v1.UpdateOptions) (*corev1beta1.PostgresDatabase, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.PostgresDatabase, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.PostgresDatabaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.PostgresDatabase, err error)
	Apply(ctx context.Context, postgresDatabase *applyconfigurationcorev1beta1.PostgresDatabaseApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.PostgresDatabase, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, postgresDatabase *applyconfigurationcorev1beta1.PostgresDatabaseApplyConfiguration, opts v1.ApplyOptions) (result *corev1beta1.PostgresDatabase, err error)
	PostgresDatabaseExpansion
}

// postgresDatabases implements PostgresDatabaseInterface
type postgresDatabases struct {
	*gentype.ClientWithListAndApply[*corev1beta1.PostgresDatabase, *corev1beta1.PostgresDatabaseList, *applyconfigurationcorev1beta1.PostgresDatabaseApplyConfiguration]
}

// newPostgresDatabases returns a PostgresDatabases
func newPostgresDatabases(c *CoreV1beta1Client, namespace string) *postgresDatabases {
	return &postgresDatabases{
		gentype.NewClientWithListAndApply[*corev1beta1.PostgresDatabase, *corev1beta1.PostgresDatabaseList, *applyconfigurationcorev1beta1.PostgresDatabaseApplyConfiguration](
			"postgresdatabases",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1beta1.PostgresDatabase { return &corev1beta1.PostgresDatabase{} },
			func() *corev1beta1.PostgresDatabaseList { return &corev1beta1.PostgresDatabaseList{} },
		),
	}
}
