// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated fake clientset.
package fake
