// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2026 Posit Software, PBC

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"

	keycloakv2alpha1 "github.com/posit-dev/team-operator/api/keycloak/v2alpha1"
	applyconfigurationkeycloakv2alpha1 "github.com/posit-dev/team-operator/client-go/applyconfiguration/keycloak/v2alpha1"
	scheme "github.com/posit-dev/team-operator/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KeycloaksGetter has a method to return a KeycloakInterface.
// A group's client should implement this interface.
type KeycloaksGetter interface {
	Keycloaks(namespace string) KeycloakInterface
}

// KeycloakInterface has methods to work with Keycloak resources.
type KeycloakInterface interface {
	Create(ctx context.Context, keycloak *keycloakv2alpha1.Keycloak, opts v1.CreateOptions) (*keycloakv2alpha1.Keycloak, error)
	Update(ctx context.Context, keycloak *keycloakv2alpha1.Keycloak, opts v1.UpdateOptions) (*keycloakv2alpha1.Keycloak, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, keycloak *keycloakv2alpha1.Keycloak, opts v1.UpdateOptions) (*keycloakv2alpha1.Keycloak, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*keycloakv2alpha1.Keycloak, error)
	List(ctx context.Context, opts v1.ListOptions) (*keycloakv2alpha1.KeycloakList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *keycloakv2alpha1.Keycloak, err error)
	Apply(ctx context.Context, keycloak *applyconfigurationkeycloakv2alpha1.KeycloakApplyConfiguration, opts v1.ApplyOptions) (result *keycloakv2alpha1.Keycloak, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, keycloak *applyconfigurationkeycloakv2alpha1.KeycloakApplyConfiguration, opts v1.ApplyOptions) (result *keycloakv2alpha1.Keycloak, err error)
	KeycloakExpansion
}

// keycloaks implements KeycloakInterface
type keycloaks struct {
	*gentype.ClientWithListAndApply[*keycloakv2alpha1.Keycloak, *keycloakv2alpha1.KeycloakList, *applyconfigurationkeycloakv2alpha1.KeycloakApplyConfiguration]
}

// newKeycloaks returns a Keycloaks
func newKeycloaks(c *KeycloakV2alpha1Client, namespace string) *keycloaks {
	return &keycloaks{
		gentype.NewClientWithListAndApply[*keycloakv2alpha1.Keycloak, *keycloakv2alpha1.KeycloakList, *applyconfigurationkeycloakv2alpha1.KeycloakApplyConfiguration](
			"keycloaks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *keycloakv2alpha1.Keycloak { return &keycloakv2alpha1.Keycloak{} },
			func() *keycloakv2alpha1.KeycloakList { return &keycloakv2alpha1.KeycloakList{} },
		),
	}
}
