// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2025 Posit Software, PBC
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	keycloakv2alpha1 "github.com/posit-dev/team-operator/api/keycloak/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KeycloakLister helps list Keycloaks.
// All objects returned here must be treated as read-only.
type KeycloakLister interface {
	// List lists all Keycloaks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*keycloakv2alpha1.Keycloak, err error)
	// Keycloaks returns an object that can list and get Keycloaks.
	Keycloaks(namespace string) KeycloakNamespaceLister
	KeycloakListerExpansion
}

// keycloakLister implements the KeycloakLister interface.
type keycloakLister struct {
	listers.ResourceIndexer[*keycloakv2alpha1.Keycloak]
}

// NewKeycloakLister returns a new KeycloakLister.
func NewKeycloakLister(indexer cache.Indexer) KeycloakLister {
	return &keycloakLister{listers.New[*keycloakv2alpha1.Keycloak](indexer, keycloakv2alpha1.Resource("keycloak"))}
}

// Keycloaks returns an object that can list and get Keycloaks.
func (s *keycloakLister) Keycloaks(namespace string) KeycloakNamespaceLister {
	return keycloakNamespaceLister{listers.NewNamespaced[*keycloakv2alpha1.Keycloak](s.ResourceIndexer, namespace)}
}

// KeycloakNamespaceLister helps list and get Keycloaks.
// All objects returned here must be treated as read-only.
type KeycloakNamespaceLister interface {
	// List lists all Keycloaks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*keycloakv2alpha1.Keycloak, err error)
	// Get retrieves the Keycloak from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*keycloakv2alpha1.Keycloak, error)
	KeycloakNamespaceListerExpansion
}

// keycloakNamespaceLister implements the KeycloakNamespaceLister
// interface.
type keycloakNamespaceLister struct {
	listers.ResourceIndexer[*keycloakv2alpha1.Keycloak]
}
